// Common ingredient/allergen translations for fallback when backend doesn't provide per-item translations

type LangCode = "nl" | "en" | "fr" | "es" | "de" | "it" | "hu" | "id" | "tr" | "vi" | "th" | "uk" | "pt" | "ru" | "hi" | "pl" | "zh" | "ja" | "ko" | "ar";

const translations: Record<string, Partial<Record<LangCode, string>>> = {
  // Allergens
  gluten: { nl: "Gluten", en: "Gluten", fr: "Gluten", es: "Gluten", de: "Gluten", it: "Glutine", hu: "Glutén", id: "Gluten", tr: "Gluten", vi: "Gluten", th: "กลูเตน", uk: "Глютен", pt: "Glúten", ru: "Глютен", hi: "ग्लूटेन", pl: "Gluten", zh: "麸质", ja: "グルテン", ko: "글루텐", ar: "الغلوتين" },
  lactose: { nl: "Lactose", en: "Lactose", fr: "Lactose", es: "Lactosa", de: "Laktose", it: "Lattosio", hu: "Laktóz", id: "Laktosa", tr: "Laktoz", vi: "Lactose", th: "แลคโตส", uk: "Лактоза", pt: "Lactose", ru: "Лактоза", hi: "लैक्टोज", pl: "Laktoza", zh: "乳糖", ja: "乳糖", ko: "유당", ar: "اللاكتوز" },
  noten: { nl: "Noten", en: "Nuts", fr: "Noix", es: "Frutos secos", de: "Nüsse", it: "Frutta a guscio", hu: "Diófélék", id: "Kacang", tr: "Kuruyemiş", vi: "Hạt", th: "ถั่ว", uk: "Горіхи", pt: "Frutos secos", ru: "Орехи", hi: "मेवे", pl: "Orzechy", zh: "坚果", ja: "ナッツ", ko: "견과류", ar: "المكسرات" },
  nuts: { nl: "Noten", en: "Nuts", fr: "Noix", es: "Frutos secos", de: "Nüsse", it: "Frutta a guscio", hu: "Diófélék", id: "Kacang", tr: "Kuruyemiş", vi: "Hạt", th: "ถั่ว", uk: "Горіхи", pt: "Frutos secos", ru: "Орехи", hi: "मेवे", pl: "Orzechy", zh: "坚果", ja: "ナッツ", ko: "견과류", ar: "المكسرات" },
  schaaldieren: { nl: "Schaaldieren", en: "Shellfish", fr: "Crustacés", es: "Mariscos", de: "Schalentiere", it: "Crostacei", hu: "Rákfélék", id: "Kerang", tr: "Kabuklu deniz ürünleri", vi: "Động vật có vỏ", th: "หอย", uk: "Молюски", pt: "Mariscos", ru: "Моллюски", hi: "शंख", pl: "Skorupiaki", zh: "贝类", ja: "甲殻類", ko: "갑각류", ar: "المحار" },
  shellfish: { nl: "Schaaldieren", en: "Shellfish", fr: "Crustacés", es: "Mariscos", de: "Schalentiere", it: "Crostacei", hu: "Rákfélék", id: "Kerang", tr: "Kabuklu deniz ürünleri", vi: "Động vật có vỏ", th: "หอย", uk: "Молюски", pt: "Mariscos", ru: "Моллюски", hi: "शंख", pl: "Skorupiaki", zh: "贝类", ja: "甲殻類", ko: "갑각류", ar: "المحار" },
  vis: { nl: "Vis", en: "Fish", fr: "Poisson", es: "Pescado", de: "Fisch", it: "Pesce", hu: "Hal", id: "Ikan", tr: "Balık", vi: "Cá", th: "ปลา", uk: "Риба", pt: "Peixe", ru: "Рыба", hi: "मछली", pl: "Ryba", zh: "鱼", ja: "魚", ko: "생선", ar: "السمك" },
  fish: { nl: "Vis", en: "Fish", fr: "Poisson", es: "Pescado", de: "Fisch", it: "Pesce", hu: "Hal", id: "Ikan", tr: "Balık", vi: "Cá", th: "ปลา", uk: "Риба", pt: "Peixe", ru: "Рыба", hi: "मछली", pl: "Ryba", zh: "鱼", ja: "魚", ko: "생선", ar: "السمك" },
  eieren: { nl: "Eieren", en: "Eggs", fr: "Œufs", es: "Huevos", de: "Eier", it: "Uova", hu: "Tojás", id: "Telur", tr: "Yumurta", vi: "Trứng", th: "ไข่", uk: "Яйця", pt: "Ovos", ru: "Яйца", hi: "अंडे", pl: "Jajka", zh: "鸡蛋", ja: "卵", ko: "달걀", ar: "البيض" },
  eggs: { nl: "Eieren", en: "Eggs", fr: "Œufs", es: "Huevos", de: "Eier", it: "Uova", hu: "Tojás", id: "Telur", tr: "Yumurta", vi: "Trứng", th: "ไข่", uk: "Яйця", pt: "Ovos", ru: "Яйца", hi: "अंडे", pl: "Jajka", zh: "鸡蛋", ja: "卵", ko: "달걀", ar: "البيض" },
  soja: { nl: "Soja", en: "Soy", fr: "Soja", es: "Soja", de: "Soja", it: "Soia", hu: "Szója", id: "Kedelai", tr: "Soya", vi: "Đậu nành", th: "ถั่วเหลือง", uk: "Соя", pt: "Soja", ru: "Соя", hi: "सोया", pl: "Soja", zh: "大豆", ja: "大豆", ko: "대두", ar: "الصويا" },
  soy: { nl: "Soja", en: "Soy", fr: "Soja", es: "Soja", de: "Soja", it: "Soia", hu: "Szója", id: "Kedelai", tr: "Soya", vi: "Đậu nành", th: "ถั่วเหลือง", uk: "Соя", pt: "Soja", ru: "Соя", hi: "सोया", pl: "Soja", zh: "大豆", ja: "大豆", ko: "대두", ar: "الصويا" },
  sulfiet: { nl: "Sulfiet", en: "Sulfite", fr: "Sulfites", es: "Sulfitos", de: "Sulfite", it: "Solfiti", hu: "Szulfit", id: "Sulfit", tr: "Sülfit", vi: "Sulfit", th: "ซัลไฟต์", uk: "Сульфіти", pt: "Sulfitos", ru: "Сульфиты", hi: "सल्फाइट", pl: "Siarczyny", zh: "亚硫酸盐", ja: "亜硫酸塩", ko: "아황산염", ar: "الكبريتيت" },
  sulfite: { nl: "Sulfiet", en: "Sulfite", fr: "Sulfites", es: "Sulfitos", de: "Sulfite", it: "Solfiti", hu: "Szulfit", id: "Sulfit", tr: "Sülfit", vi: "Sulfit", th: "ซัลไฟต์", uk: "Сульфіти", pt: "Sulfitos", ru: "Сульфиты", hi: "सल्फाइट", pl: "Siarczyny", zh: "亚硫酸盐", ja: "亜硫酸塩", ko: "아황산염", ar: "الكبريتيت" },
  "pinda's": { nl: "Pinda's", en: "Peanuts", fr: "Arachides", es: "Cacahuetes", de: "Erdnüsse", it: "Arachidi", hu: "Földimogyoró", id: "Kacang tanah", tr: "Yer fıstığı", vi: "Đậu phộng", th: "ถั่วลิสง", uk: "Арахіс", pt: "Amendoins", ru: "Арахис", hi: "मूंगफली", pl: "Orzeszki ziemne", zh: "花生", ja: "ピーナッツ", ko: "땅콩", ar: "الفول السوداني" },
  peanuts: { nl: "Pinda's", en: "Peanuts", fr: "Arachides", es: "Cacahuetes", de: "Erdnüsse", it: "Arachidi", hu: "Földimogyoró", id: "Kacang tanah", tr: "Yer fıstığı", vi: "Đậu phộng", th: "ถั่วลิสง", uk: "Арахіс", pt: "Amendoins", ru: "Арахис", hi: "मूंगफली", pl: "Orzeszki ziemne", zh: "花生", ja: "ピーナッツ", ko: "땅콩", ar: "الفول السوداني" },
  sesam: { nl: "Sesam", en: "Sesame", fr: "Sésame", es: "Sésamo", de: "Sesam", it: "Sesamo", hu: "Szezám", id: "Wijen", tr: "Susam", vi: "Mè", th: "งา", uk: "Кунжут", pt: "Sésamo", ru: "Кунжут", hi: "तिल", pl: "Sezam", zh: "芝麻", ja: "ゴマ", ko: "참깨", ar: "السمسم" },
  sesame: { nl: "Sesam", en: "Sesame", fr: "Sésame", es: "Sésamo", de: "Sesam", it: "Sesamo", hu: "Szezám", id: "Wijen", tr: "Susam", vi: "Mè", th: "งา", uk: "Кунжут", pt: "Sésamo", ru: "Кунжут", hi: "तिल", pl: "Sezam", zh: "芝麻", ja: "ゴマ", ko: "참깨", ar: "السمسم" },
  selderij: { nl: "Selderij", en: "Celery", fr: "Céleri", es: "Apio", de: "Sellerie", it: "Sedano", hu: "Zeller", id: "Seledri", tr: "Kereviz", vi: "Cần tây", th: "ขึ้นฉ่าย", uk: "Селера", pt: "Aipo", ru: "Сельдерей", hi: "अजवाइन", pl: "Seler", zh: "芹菜", ja: "セロリ", ko: "셀러리", ar: "الكرفس" },
  celery: { nl: "Selderij", en: "Celery", fr: "Céleri", es: "Apio", de: "Sellerie", it: "Sedano", hu: "Zeller", id: "Seledri", tr: "Kereviz", vi: "Cần tây", th: "ขึ้นฉ่าย", uk: "Селера", pt: "Aipo", ru: "Сельдерей", hi: "अजवाइन", pl: "Seler", zh: "芹菜", ja: "セロリ", ko: "셀러리", ar: "الكرفس" },
  mosterd: { nl: "Mosterd", en: "Mustard", fr: "Moutarde", es: "Mostaza", de: "Senf", it: "Senape", hu: "Mustár", id: "Mustard", tr: "Hardal", vi: "Mù tạt", th: "มัสตาร์ด", uk: "Гірчиця", pt: "Mostarda", ru: "Горчица", hi: "सरसों", pl: "Musztarda", zh: "芥末", ja: "マスタード", ko: "겨자", ar: "الخردل" },
  mustard: { nl: "Mosterd", en: "Mustard", fr: "Moutarde", es: "Mostaza", de: "Senf", it: "Senape", hu: "Mustár", id: "Mustard", tr: "Hardal", vi: "Mù tạt", th: "มัสตาร์ด", uk: "Гірчиця", pt: "Mostarda", ru: "Горчица", hi: "सरसों", pl: "Musztarda", zh: "芥末", ja: "マスタード", ko: "겨자", ar: "الخردل" },
  weekdieren: { nl: "Weekdieren", en: "Molluscs", fr: "Mollusques", es: "Moluscos", de: "Weichtiere", it: "Molluschi", hu: "Puhatestűek", id: "Moluska", tr: "Yumuşakçalar", vi: "Động vật thân mềm", th: "หอยทาก", uk: "Молюски", pt: "Moluscos", ru: "Моллюски", hi: "मोलस्क", pl: "Mięczaki", zh: "软体动物", ja: "軟体動物", ko: "연체동물", ar: "الرخويات" },
  molluscs: { nl: "Weekdieren", en: "Molluscs", fr: "Mollusques", es: "Moluscos", de: "Weichtiere", it: "Molluschi", hu: "Puhatestűek", id: "Moluska", tr: "Yumuşakçalar", vi: "Động vật thân mềm", th: "หอยทาก", uk: "Молюски", pt: "Moluscos", ru: "Моллюски", hi: "मोलस्क", pl: "Mięczaki", zh: "软体动物", ja: "軟体動物", ko: "연체동물", ar: "الرخويات" },
  lupine: { nl: "Lupine", en: "Lupin", fr: "Lupin", es: "Altramuz", de: "Lupinen", it: "Lupino", hu: "Csillagfürt", id: "Lupin", tr: "Acı bakla", vi: "Lupin", th: "ลูปิน", uk: "Люпин", pt: "Tremoço", ru: "Люпин", hi: "ल्यूपिन", pl: "Łubin", zh: "羽扇豆", ja: "ルピナス", ko: "루핀", ar: "الترمس" },
  lupin: { nl: "Lupine", en: "Lupin", fr: "Lupin", es: "Altramuz", de: "Lupinen", it: "Lupino", hu: "Csillagfürt", id: "Lupin", tr: "Acı bakla", vi: "Lupin", th: "ลูปิน", uk: "Люпин", pt: "Tremoço", ru: "Люпин", hi: "ल्यूपिन", pl: "Łubin", zh: "羽扇豆", ja: "ルピナス", ko: "루핀", ar: "الترمس" },
  // Dietary info
  vegetarisch: { nl: "Vegetarisch", en: "Vegetarian", fr: "Végétarien", es: "Vegetariano", de: "Vegetarisch", it: "Vegetariano", hu: "Vegetáriánus", id: "Vegetarian", tr: "Vejetaryen", vi: "Chay", th: "มังสวิรัติ", uk: "Вегетаріанський", pt: "Vegetariano", ru: "Вегетарианский", hi: "शाकाहारी", pl: "Wegetariański", zh: "素食", ja: "ベジタリアン", ko: "채식", ar: "نباتي" },
  vegetarian: { nl: "Vegetarisch", en: "Vegetarian", fr: "Végétarien", es: "Vegetariano", de: "Vegetarisch", it: "Vegetariano", hu: "Vegetáriánus", id: "Vegetarian", tr: "Vejetaryen", vi: "Chay", th: "มังสวิรัติ", uk: "Вегетаріанський", pt: "Vegetariano", ru: "Вегетарианский", hi: "शाकाहारी", pl: "Wegetariański", zh: "素食", ja: "ベジタリアン", ko: "채식", ar: "نباتي" },
  veganistisch: { nl: "Veganistisch", en: "Vegan", fr: "Végan", es: "Vegano", de: "Vegan", it: "Vegano", hu: "Vegán", id: "Vegan", tr: "Vegan", vi: "Thuần chay", th: "วีแกน", uk: "Веганський", pt: "Vegano", ru: "Веганский", hi: "शुद्ध शाकाहारी", pl: "Wegański", zh: "纯素", ja: "ビーガン", ko: "비건", ar: "نباتي صرف" },
  vegan: { nl: "Veganistisch", en: "Vegan", fr: "Végan", es: "Vegano", de: "Vegan", it: "Vegano", hu: "Vegán", id: "Vegan", tr: "Vegan", vi: "Thuần chay", th: "วีแกน", uk: "Веганський", pt: "Vegano", ru: "Веганский", hi: "शुद्ध शाकाहारी", pl: "Wegański", zh: "纯素", ja: "ビーガン", ko: "비건", ar: "نباتي صرف" },
  halal: { nl: "Halal", en: "Halal", fr: "Halal", es: "Halal", de: "Halal", it: "Halal", hu: "Halal", id: "Halal", tr: "Helal", vi: "Halal", th: "ฮาลาล", uk: "Халяль", pt: "Halal", ru: "Халяль", hi: "हलाल", pl: "Halal", zh: "清真", ja: "ハラール", ko: "할랄", ar: "حلال" },
  kosher: { nl: "Koosjer", en: "Kosher", fr: "Casher", es: "Kosher", de: "Koscher", it: "Kosher", hu: "Kóser", id: "Kosher", tr: "Koşer", vi: "Kosher", th: "โคเชอร์", uk: "Кошерний", pt: "Kosher", ru: "Кошерный", hi: "कोषेर", pl: "Koszerny", zh: "犹太洁食", ja: "コーシャ", ko: "코셔", ar: "كوشير" },
};

export function translateItem(item: string, language: LangCode): string {
  const key = item.toLowerCase().trim();
  const entry = translations[key];
  if (entry && entry[language]) {
    return entry[language]!;
  }
  // Return original with first letter capitalized
  return item.charAt(0).toUpperCase() + item.slice(1);
}
