import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "nl" | "en" | "fr" | "es" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Index page
    "index.title": "Vind je perfecte maaltijd",
    "index.subtitle": "Match je allergieën en voorkeuren met restaurants",
    "index.scanMenu": "Scan Menu",
    "index.myProfile": "Mijn Profiel",
    "index.signIn": "Inloggen",
    "index.feature1Title": "Scan & Herken",
    "index.feature1Desc": "Scan menukaarten direct met je camera en laat AI de ingrediënten analyseren",
    "index.feature2Title": "Veiligheid Eerst",
    "index.feature2Desc": "Krijg direct duidelijke waarschuwingen voor jouw specifieke allergieën",
    "index.feature3Title": "Persoonlijk",
    "index.feature3Desc": "Sla je allergieën en voorkeuren op voor snellere controles",
    "index.howItWorksTitle": "Zo werkt het",
    "index.howItWorksDesc": "Veilig dineren in 3 simpele stappen",
    "index.step1Title": "Stel je voorkeuren in",
    "index.step1Desc": "Voeg je allergieën, dieetwensen en voorkeuren toe aan je profiel. Dit hoef je maar één keer te doen.",
    "index.step2Title": "Scan de menukaart",
    "index.step2Desc": "Gebruik je camera om de menukaart te scannen, of upload een foto. Onze AI doet de rest.",
    "index.step3Title": "Zie direct wat veilig is",
    "index.step3Desc": "Elk gerecht krijgt een smiley: 😊 veilig, 😐 aanpasbaar, of 🤢 bevat allergenen.",
    "index.readyTitle": "Klaar om veilig te genieten?",
    "index.readyDesc": "Begin nu met scannen en ontdek veilige maaltijden",
    
    // Allergies
    "allergy.noten": "Noten",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Lactose",
    "allergy.schaaldieren": "Schaaldieren",
    "allergy.vis": "Vis",
    "allergy.eieren": "Eieren",
    "allergy.soja": "Soja",
    "allergy.sulfiet": "Sulfiet",
    
    // Preferences
    "preference.vegetarisch": "Vegetarisch",
    "preference.veganistisch": "Veganistisch",
    "preference.halal": "Halal",
    "preference.kosher": "Kosher",
    
    // Scan page
    "scan.title": "Menu Scannen",
    "scan.subtitle": "Kies hoe je de menukaart wilt uploaden",
    "scan.camera": "Camera",
    "scan.cameraDesc": "Scan direct met je camera",
    "scan.upload": "Upload",
    "scan.uploadDesc": "Upload een foto of PDF",
    "scan.multiple": "Meerdere Foto's",
    "scan.multipleDesc": "Combineer verschillende pagina's",
    "scan.analyzing": "Analyseren...",
    "scan.analyzingDesc": "De AI analyseert je menu. Dit kan even duren.",
    "scan.analyzingMultiple": "De AI analyseert {count} foto{s}. Dit kan even duren.",
    "scan.checkPhoto": "Controleer je foto",
    "scan.readable": "Is de menukaart goed leesbaar?",
    "scan.retry": "Opnieuw",
    "scan.scanButton": "Scannen",
    "scan.back": "Terug",
    "scan.tipsTitle": "💡 Tips voor beste resultaten:",
    "scan.tip1": "Zorg voor goede verlichting",
    "scan.tip2": "Houd de camera stabiel",
    "scan.tip3": "Zorg dat de tekst goed leesbaar is",
    "scan.makePhoto": "Maak een foto",
    "scan.position": "Positioneer de menukaart in beeld",
    "scan.cancel": "Annuleren",
    "scan.takePhoto": "Foto Maken",
    "scan.multipleTitle": "Meerdere Foto's",
    "scan.photosAdded": "{count} foto{s} toegevoegd",
    "scan.addPhotos": "Voeg foto's van verschillende menupagina's toe",
    "scan.addMore": "Meer Foto's Toevoegen",
    "scan.scanMultiple": "Scan {count} Foto{s}",
    "scan.page": "Pagina",
    "scan.errorTitle": "Oeps, dat ging niet goed",
    "scan.tryAgain": "Probeer Opnieuw",
    "scan.suggestionsTitle": "💡 Suggesties voor betere resultaten:",
    "scan.suggestion1": "Zorg voor goede verlichting zonder schaduwen",
    "scan.suggestion2": "Houd de camera stabiel en recht boven het menu",
    "scan.suggestion3": "Zorg dat de tekst scherp en goed leesbaar is",
    "scan.suggestion4": "Fotografeer het hele menu of een duidelijk deel ervan",
    
    // Menu Results
    "results.title": "Menu Resultaten",
    "results.found": "{count} gerechten gevonden - Gebaseerd op jouw voorkeuren en allergieën",
    "results.contains": "⚠️ Bevat:",
    "results.safe": "Veilig",
    "results.adjustable": "Aanpasbaar",
    "results.containsAllergens": "Bevat Allergenen",
    "results.dishes": "gerechten",
    
    // Profile page
    "profile.title": "Mijn Profiel",
    "profile.subtitle": "Stel je allergieën en voorkeuren in voor gepersonaliseerde matches",
    "profile.businessSubtitle": "Beheer je bedrijfsinstellingen",
    "profile.allergies": "🚫 Allergieën",
    "profile.allergiesDesc": "Selecteer alle allergieën waar we rekening mee moeten houden",
    "profile.addCustom": "Eigen allergie toevoegen",
    "profile.customDesc": "Voeg een allergie toe die niet in de lijst staat, inclusief ingrediënten die we moeten detecteren",
    "profile.allergyName": "Allergie naam",
    "profile.allergyNamePlaceholder": "Bijv: Sesam",
    "profile.characteristics": "Kenmerken (gescheiden door komma's)",
    "profile.characteristicsPlaceholder": "Bijv: sesamzaad, sesam olie, tahini",
    "profile.characteristicsHelp": "Deze ingrediënten worden gedetecteerd op menukaarten",
    "profile.addAllergy": "Allergie Toevoegen",
    "profile.yourAllergies": "Jouw allergieën:",
    "profile.preferences": "❤️ Dieetvoorkeuren",
    "profile.preferencesDesc": "Selecteer je dieetwensen",
    "profile.save": "Opslaan",
    "profile.saving": "Opslaan...",
    "profile.logout": "Uitloggen",
    "profile.businessDashboard": "Bedrijf Dashboard",
    "profile.adminDashboard": "Admin Dashboard",
    "profile.saved": "Profiel opgeslagen! ✓",
    "profile.savedDesc": "Je voorkeuren zijn succesvol bijgewerkt.",
    "profile.savedGuestDesc": "Je voorkeuren zijn tijdelijk opgeslagen.",
    
    // Auth page
    "auth.welcome": "Welkom bij Bite Buddy",
    "auth.subtitle": "Match je allergieën met perfecte maaltijden",
    "auth.userType": "Ik ben een...",
    "auth.diner": "Eter",
    "auth.dinerDesc": "Ik zoek veilige restaurants",
    "auth.business": "Eetgever",
    "auth.businessDesc": "Ik heb een restaurant",
    "auth.signUp": "Aanmelden",
    "auth.signIn": "Inloggen",
    "auth.continueAsGuest": "Doorgaan als Gast",
    "auth.email": "Email",
    "auth.password": "Wachtwoord",
    "auth.alreadyAccount": "Heb je al een account?",
    "auth.noAccount": "Nog geen account?",
    "auth.signUpLink": "Aanmelden",
    "auth.signInLink": "Inloggen",
    
    // Menu View
    "menuView.title": "Menu",
    "menuView.dishesAvailable": "{count} gerechten beschikbaar",
    "menuView.noDishes": "Dit menu heeft nog geen gerechten",
    "menuView.yourAllergies": "Je allergieën:",
    "menuView.compareAllergies": "Vergelijk met mijn allergieën",
    "menuView.comparing": "Bezig met vergelijken...",
    "menuView.results": "Resultaten:",
    "menuView.foundAllergens": "Gevonden allergenen:",
    "menuView.otherAllergensWarning": "Bevat andere allergenen. Vraag personeel om aanpassingen.",
    "menuView.noDishesAdded": "Dit menu heeft nog geen gerechten toegevoegd.",
    "menuView.loginRequired": "Inloggen vereist",
    "menuView.loginRequiredDesc": "Log in om je allergieën te vergelijken met het menu.",
    "menuView.loginToCompare": "Log in of ga door als gast om je allergieën te vergelijken met dit menu",
    "menuView.menuNotFound": "Menu niet gevonden",
    "menuView.invalidQR": "Deze QR-code is niet geldig.",
    "menuView.comparisonComplete": "Vergelijking compleet!",
    "menuView.comparisonCompleteDesc": "Je allergieën zijn vergeleken met het menu.",
    "menuView.errorScanning": "Fout bij scannen",
    "menuView.errorLoading": "Fout bij laden",
    "menuView.backToHome": "Terug naar Home",
    
    // Business Dashboard
    "business.title": "Bedrijf Dashboard",
    "business.subtitle": "Bekijk je menu's en scan statistieken",
    "business.totalMenus": "Totaal Menu's",
    "business.totalScans": "Totaal Scans",
    "business.uniqueAllergies": "Unieke Allergieën/Voorkeuren",
    "business.topAllergies": "Top 5 Allergieën & Voorkeuren",
    "business.topAllergiesDesc": "Meest gescande allergieën en voorkeuren",
    "business.allAllergies": "Alle Allergieën & Voorkeuren",
    "business.allAllergiesDesc": "Volledige lijst van gescande allergieën en voorkeuren",
    "business.timesScanned": "{count}x gescand",
    "business.myMenus": "Mijn Menu's",
    "business.myMenusDesc": "Beheer je gescande menu's en bekijk QR-codes",
    "business.noMenus": "Je hebt nog geen menu's gescand",
    "business.scanFirstMenu": "Scan je eerste menu",
    "business.createdOn": "Gemaakt op {date}",
    "business.qrCode": "QR Code: {code}",
    "business.viewQR": "Bekijk QR",
    "business.addNewMenu": "Nieuw Menu Toevoegen",
    "business.addNewMenuDesc": "Betaal €1,00 per menu om te beginnen met scannen",
    "business.payAndScan": "Betaal €1,00 en Scan Menu",
    "business.processingPayment": "Bezig met betaling...",
    "business.noAccess": "Geen toegang",
    "business.businessOnly": "Deze pagina is alleen voor bedrijven.",
    "business.notLoggedIn": "Niet ingelogd",
    "business.loginToContinue": "Log in om door te gaan",
    "business.paymentError": "Fout bij betaling",
    "business.backToProfile": "Terug naar Profiel",
    
    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Overzicht van app statistieken",
    "admin.totalUsers": "Totaal Accounts",
    "admin.totalScans": "Totaal Scans",
    "admin.uniquePreferences": "Unieke Voorkeuren",
    "admin.registeredUsers": "Geregistreerde gebruikers",
    "admin.menusScanned": "Menu's gescand",
    "admin.differentPreferences": "Verschillende voorkeuren",
    "admin.adAnalytics": "Reclame Analytics",
    "admin.totalShown": "Totaal Getoond",
    "admin.completionRate": "Voltooiingspercentage",
    "admin.fullyWatched": "Volledig Bekeken",
    "admin.skipped": "Overgeslagen",
    "admin.avgSkipCountdown": "Gem. Skip Countdown",
    "admin.completionVsSkip": "Voltooiing vs. Skip",
    "admin.total": "{count} totaal",
    "admin.completed": "Volledig ({count})",
    "admin.skippedCount": "Overgeslagen ({count})",
    "admin.noAdAnalytics": "Nog geen reclame analytics beschikbaar",
    "admin.preferencesOverview": "Voorkeuren Overzicht",
    "admin.noPreferences": "Nog geen voorkeuren geregistreerd",
    "admin.loadingStats": "Statistieken laden...",
    "admin.noAccess": "Geen toegang",
    "admin.noAdminRights": "Je hebt geen admin rechten.",
    "admin.errorLoadingStats": "Kon statistieken niet laden.",
    
    // Menu Editor
    "editor.title": "Menu Bewerken",
    "editor.subtitle": "Voeg gerechten toe en specificeer ingrediënten en allergenen",
    "editor.backToDashboard": "Terug naar Dashboard",
    "editor.defaultAllergens": "Standaard Allergenen",
    "editor.defaultAllergensDesc": "Deze allergenen worden automatisch aan alle gerechten toegevoegd",
    "editor.addDish": "Nieuw Gerecht Toevoegen",
    "editor.dishName": "Naam Gerecht",
    "editor.dishNamePlaceholder": "Bijv. Caesar Salade",
    "editor.price": "Prijs",
    "editor.description": "Beschrijving",
    "editor.descriptionPlaceholder": "Korte beschrijving van het gerecht",
    "editor.ingredients": "Ingrediënten",
    "editor.addIngredient": "Voeg ingrediënt toe",
    "editor.extraAllergens": "Extra Allergenen (naast standaard)",
    "editor.addDishBtn": "Gerecht Toevoegen",
    "editor.saving": "Opslaan...",
    "editor.addedDishes": "Toegevoegde Gerechten",
    "editor.finishEditing": "Klaar met Bewerken",
    "editor.incomplete": "Onvolledig",
    "editor.incompleteDesc": "Vul minimaal een naam en ingrediënten in",
    "editor.dishAdded": "Gerecht toegevoegd!",
    "editor.dishAddedDesc": "{name} is toegevoegd aan het menu",
    "editor.loadError": "Fout bij laden",
    "editor.saveError": "Fout bij opslaan",
    
    // Common
    "common.loading": "Laden...",
    "common.error": "Fout",
    "common.success": "Gelukt",
    "common.back": "Terug",
    "common.close": "Sluiten",
    "common.save": "Opslaan",
    "common.cancel": "Annuleren",
    "common.delete": "Verwijderen",
    "common.edit": "Bewerken",
    "common.add": "Toevoegen",
    "common.login": "Inloggen",
    "common.continueAsGuest": "Doorgaan als Gast",
  },
  en: {
    // Index page
    "index.title": "Find your perfect meal",
    "index.subtitle": "Match your allergies and preferences with restaurants",
    "index.scanMenu": "Scan Menu",
    "index.myProfile": "My Profile",
    "index.signIn": "Sign In",
    "index.feature1Title": "Scan & Recognize",
    "index.feature1Desc": "Scan menus directly with your camera and let AI analyze the ingredients",
    "index.feature2Title": "Safety First",
    "index.feature2Desc": "Get immediate clear warnings for your specific allergies",
    "index.feature3Title": "Personal",
    "index.feature3Desc": "Save your allergies and preferences for faster checks",
    "index.howItWorksTitle": "How it works",
    "index.howItWorksDesc": "Safe dining in 3 simple steps",
    "index.step1Title": "Set your preferences",
    "index.step1Desc": "Add your allergies, dietary needs and preferences to your profile. You only need to do this once.",
    "index.step2Title": "Scan the menu",
    "index.step2Desc": "Use your camera to scan the menu, or upload a photo. Our AI does the rest.",
    "index.step3Title": "See immediately what's safe",
    "index.step3Desc": "Each dish gets a smiley: 😊 safe, 😐 adjustable, or 🤢 contains allergens.",
    "index.readyTitle": "Ready to enjoy safely?",
    "index.readyDesc": "Start scanning now and discover safe meals",
    
    // Allergies
    "allergy.noten": "Nuts",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Lactose",
    "allergy.schaaldieren": "Shellfish",
    "allergy.vis": "Fish",
    "allergy.eieren": "Eggs",
    "allergy.soja": "Soy",
    "allergy.sulfiet": "Sulfites",
    
    // Preferences
    "preference.vegetarisch": "Vegetarian",
    "preference.veganistisch": "Vegan",
    "preference.halal": "Halal",
    "preference.kosher": "Kosher",
    
    // Scan page
    "scan.title": "Scan Menu",
    "scan.subtitle": "Choose how to upload the menu",
    "scan.camera": "Camera",
    "scan.cameraDesc": "Scan directly with your camera",
    "scan.upload": "Upload",
    "scan.uploadDesc": "Upload a photo or PDF",
    "scan.multiple": "Multiple Photos",
    "scan.multipleDesc": "Combine different pages",
    "scan.analyzing": "Analyzing...",
    "scan.analyzingDesc": "AI is analyzing your menu. This may take a moment.",
    "scan.analyzingMultiple": "AI is analyzing {count} photo{s}. This may take a moment.",
    "scan.checkPhoto": "Check your photo",
    "scan.readable": "Is the menu clearly readable?",
    "scan.retry": "Retry",
    "scan.scanButton": "Scan",
    "scan.back": "Back",
    "scan.tipsTitle": "💡 Tips for best results:",
    "scan.tip1": "Ensure good lighting",
    "scan.tip2": "Hold the camera steady",
    "scan.tip3": "Make sure text is clearly readable",
    "scan.makePhoto": "Take a photo",
    "scan.position": "Position the menu in view",
    "scan.cancel": "Cancel",
    "scan.takePhoto": "Take Photo",
    "scan.multipleTitle": "Multiple Photos",
    "scan.photosAdded": "{count} photo{s} added",
    "scan.addPhotos": "Add photos of different menu pages",
    "scan.addMore": "Add More Photos",
    "scan.scanMultiple": "Scan {count} Photo{s}",
    "scan.page": "Page",
    "scan.errorTitle": "Oops, something went wrong",
    "scan.tryAgain": "Try Again",
    "scan.suggestionsTitle": "💡 Suggestions for better results:",
    "scan.suggestion1": "Ensure good lighting without shadows",
    "scan.suggestion2": "Hold the camera steady and directly above the menu",
    "scan.suggestion3": "Make sure the text is sharp and clearly readable",
    "scan.suggestion4": "Photograph the entire menu or a clear portion of it",
    
    // Menu Results
    "results.title": "Menu Results",
    "results.found": "{count} dishes found - Based on your preferences and allergies",
    "results.contains": "⚠️ Contains:",
    "results.safe": "Safe",
    "results.adjustable": "Adjustable",
    "results.containsAllergens": "Contains Allergens",
    "results.dishes": "dishes",
    
    // Profile page
    "profile.title": "My Profile",
    "profile.subtitle": "Set your allergies and preferences for personalized matches",
    "profile.businessSubtitle": "Manage your business settings",
    "profile.allergies": "🚫 Allergies",
    "profile.allergiesDesc": "Select all allergies we should consider",
    "profile.addCustom": "Add custom allergy",
    "profile.customDesc": "Add an allergy not in the list, including ingredients we should detect",
    "profile.allergyName": "Allergy name",
    "profile.allergyNamePlaceholder": "E.g: Sesame",
    "profile.characteristics": "Characteristics (comma separated)",
    "profile.characteristicsPlaceholder": "E.g: sesame seeds, sesame oil, tahini",
    "profile.characteristicsHelp": "These ingredients will be detected on menus",
    "profile.addAllergy": "Add Allergy",
    "profile.yourAllergies": "Your allergies:",
    "profile.preferences": "❤️ Dietary Preferences",
    "profile.preferencesDesc": "Select your dietary preferences",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.logout": "Logout",
    "profile.businessDashboard": "Business Dashboard",
    "profile.adminDashboard": "Admin Dashboard",
    "profile.saved": "Profile saved! ✓",
    "profile.savedDesc": "Your preferences have been updated successfully.",
    "profile.savedGuestDesc": "Your preferences have been temporarily saved.",
    
    // Auth page
    "auth.welcome": "Welcome to Bite Buddy",
    "auth.subtitle": "Match your allergies with perfect meals",
    "auth.userType": "I am a...",
    "auth.diner": "Diner",
    "auth.dinerDesc": "I'm looking for safe restaurants",
    "auth.business": "Restaurant",
    "auth.businessDesc": "I have a restaurant",
    "auth.signUp": "Sign Up",
    "auth.signIn": "Sign In",
    "auth.continueAsGuest": "Continue as Guest",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.alreadyAccount": "Already have an account?",
    "auth.noAccount": "Don't have an account?",
    "auth.signUpLink": "Sign Up",
    "auth.signInLink": "Sign In",
    
    // Menu View
    "menuView.title": "Menu",
    "menuView.dishesAvailable": "{count} dishes available",
    "menuView.noDishes": "This menu has no dishes yet",
    "menuView.yourAllergies": "Your allergies:",
    "menuView.compareAllergies": "Compare with my allergies",
    "menuView.comparing": "Comparing...",
    "menuView.results": "Results:",
    "menuView.foundAllergens": "Found allergens:",
    "menuView.otherAllergensWarning": "Contains other allergens. Ask staff for modifications.",
    "menuView.noDishesAdded": "This menu has no dishes added yet.",
    "menuView.loginRequired": "Login required",
    "menuView.loginRequiredDesc": "Log in to compare your allergies with the menu.",
    "menuView.loginToCompare": "Log in or continue as guest to compare your allergies with this menu",
    "menuView.menuNotFound": "Menu not found",
    "menuView.invalidQR": "This QR code is not valid.",
    "menuView.comparisonComplete": "Comparison complete!",
    "menuView.comparisonCompleteDesc": "Your allergies have been compared with the menu.",
    "menuView.errorScanning": "Error scanning",
    "menuView.errorLoading": "Error loading",
    "menuView.backToHome": "Back to Home",
    
    // Business Dashboard
    "business.title": "Business Dashboard",
    "business.subtitle": "View your menus and scan statistics",
    "business.totalMenus": "Total Menus",
    "business.totalScans": "Total Scans",
    "business.uniqueAllergies": "Unique Allergies/Preferences",
    "business.topAllergies": "Top 5 Allergies & Preferences",
    "business.topAllergiesDesc": "Most scanned allergies and preferences",
    "business.allAllergies": "All Allergies & Preferences",
    "business.allAllergiesDesc": "Complete list of scanned allergies and preferences",
    "business.timesScanned": "{count}x scanned",
    "business.myMenus": "My Menus",
    "business.myMenusDesc": "Manage your scanned menus and view QR codes",
    "business.noMenus": "You haven't scanned any menus yet",
    "business.scanFirstMenu": "Scan your first menu",
    "business.createdOn": "Created on {date}",
    "business.qrCode": "QR Code: {code}",
    "business.viewQR": "View QR",
    "business.addNewMenu": "Add New Menu",
    "business.addNewMenuDesc": "Pay €1.00 per menu to start scanning",
    "business.payAndScan": "Pay €1.00 and Scan Menu",
    "business.processingPayment": "Processing payment...",
    "business.noAccess": "No access",
    "business.businessOnly": "This page is for businesses only.",
    "business.notLoggedIn": "Not logged in",
    "business.loginToContinue": "Log in to continue",
    "business.paymentError": "Payment error",
    "business.backToProfile": "Back to Profile",
    
    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Overview of app statistics",
    "admin.totalUsers": "Total Accounts",
    "admin.totalScans": "Total Scans",
    "admin.uniquePreferences": "Unique Preferences",
    "admin.registeredUsers": "Registered users",
    "admin.menusScanned": "Menus scanned",
    "admin.differentPreferences": "Different preferences",
    "admin.adAnalytics": "Ad Analytics",
    "admin.totalShown": "Total Shown",
    "admin.completionRate": "Completion Rate",
    "admin.fullyWatched": "Fully Watched",
    "admin.skipped": "Skipped",
    "admin.avgSkipCountdown": "Avg. Skip Countdown",
    "admin.completionVsSkip": "Completion vs. Skip",
    "admin.total": "{count} total",
    "admin.completed": "Completed ({count})",
    "admin.skippedCount": "Skipped ({count})",
    "admin.noAdAnalytics": "No ad analytics available yet",
    "admin.preferencesOverview": "Preferences Overview",
    "admin.noPreferences": "No preferences registered yet",
    "admin.loadingStats": "Loading statistics...",
    "admin.noAccess": "No access",
    "admin.noAdminRights": "You don't have admin rights.",
    "admin.errorLoadingStats": "Could not load statistics.",
    
    // Menu Editor
    "editor.title": "Edit Menu",
    "editor.subtitle": "Add dishes and specify ingredients and allergens",
    "editor.backToDashboard": "Back to Dashboard",
    "editor.defaultAllergens": "Default Allergens",
    "editor.defaultAllergensDesc": "These allergens are automatically added to all dishes",
    "editor.addDish": "Add New Dish",
    "editor.dishName": "Dish Name",
    "editor.dishNamePlaceholder": "E.g. Caesar Salad",
    "editor.price": "Price",
    "editor.description": "Description",
    "editor.descriptionPlaceholder": "Short description of the dish",
    "editor.ingredients": "Ingredients",
    "editor.addIngredient": "Add ingredient",
    "editor.extraAllergens": "Additional Allergens (besides default)",
    "editor.addDishBtn": "Add Dish",
    "editor.saving": "Saving...",
    "editor.addedDishes": "Added Dishes",
    "editor.finishEditing": "Finish Editing",
    "editor.incomplete": "Incomplete",
    "editor.incompleteDesc": "Enter at least a name and ingredients",
    "editor.dishAdded": "Dish added!",
    "editor.dishAddedDesc": "{name} has been added to the menu",
    "editor.loadError": "Error loading",
    "editor.saveError": "Error saving",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.back": "Back",
    "common.close": "Close",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.login": "Sign In",
    "common.continueAsGuest": "Continue as Guest",
  },
  fr: {
    // Index page
    "index.title": "Trouvez votre repas idéal",
    "index.subtitle": "Associez vos allergies et préférences avec les restaurants",
    "index.scanMenu": "Scanner le Menu",
    "index.myProfile": "Mon Profil",
    "index.signIn": "Se Connecter",
    "index.feature1Title": "Scanner & Reconnaître",
    "index.feature1Desc": "Scannez les menus avec votre caméra et laissez l'IA analyser les ingrédients",
    "index.feature2Title": "Sécurité Avant Tout",
    "index.feature2Desc": "Recevez des avertissements clairs pour vos allergies spécifiques",
    "index.feature3Title": "Personnel",
    "index.feature3Desc": "Enregistrez vos allergies et préférences pour des vérifications plus rapides",
    "index.howItWorksTitle": "Comment ça marche",
    "index.howItWorksDesc": "Dîner en sécurité en 3 étapes simples",
    "index.step1Title": "Définissez vos préférences",
    "index.step1Desc": "Ajoutez vos allergies et préférences à votre profil. Vous n'avez à le faire qu'une fois.",
    "index.step2Title": "Scannez le menu",
    "index.step2Desc": "Utilisez votre caméra pour scanner le menu. Notre IA fait le reste.",
    "index.step3Title": "Voyez ce qui est sûr",
    "index.step3Desc": "Chaque plat reçoit un smiley: 😊 sûr, 😐 adaptable, ou 🤢 contient des allergènes.",
    "index.readyTitle": "Prêt à déguster en sécurité?",
    "index.readyDesc": "Commencez à scanner et découvrez des repas sûrs",
    
    // Allergies
    "allergy.noten": "Noix",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Lactose",
    "allergy.schaaldieren": "Fruits de mer",
    "allergy.vis": "Poisson",
    "allergy.eieren": "Œufs",
    "allergy.soja": "Soja",
    "allergy.sulfiet": "Sulfites",
    
    // Preferences
    "preference.vegetarisch": "Végétarien",
    "preference.veganistisch": "Végétalien",
    "preference.halal": "Halal",
    "preference.kosher": "Casher",
    
    // Scan page
    "scan.title": "Scanner le Menu",
    "scan.subtitle": "Choisissez comment télécharger le menu",
    "scan.camera": "Caméra",
    "scan.cameraDesc": "Scannez directement avec votre caméra",
    "scan.upload": "Télécharger",
    "scan.uploadDesc": "Téléchargez une photo ou PDF",
    "scan.multiple": "Plusieurs Photos",
    "scan.multipleDesc": "Combinez différentes pages",
    "scan.analyzing": "Analyse en cours...",
    "scan.analyzingDesc": "L'IA analyse votre menu. Cela peut prendre un moment.",
    "scan.analyzingMultiple": "L'IA analyse {count} photo{s}. Cela peut prendre un moment.",
    "scan.checkPhoto": "Vérifiez votre photo",
    "scan.readable": "Le menu est-il clairement lisible?",
    "scan.retry": "Réessayer",
    "scan.scanButton": "Scanner",
    "scan.back": "Retour",
    "scan.tipsTitle": "💡 Conseils pour de meilleurs résultats:",
    "scan.tip1": "Assurez un bon éclairage",
    "scan.tip2": "Tenez la caméra stable",
    "scan.tip3": "Assurez-vous que le texte est lisible",
    "scan.makePhoto": "Prendre une photo",
    "scan.position": "Positionnez le menu dans le cadre",
    "scan.cancel": "Annuler",
    "scan.takePhoto": "Prendre Photo",
    "scan.multipleTitle": "Plusieurs Photos",
    "scan.photosAdded": "{count} photo{s} ajoutée{s}",
    "scan.addPhotos": "Ajoutez des photos de différentes pages du menu",
    "scan.addMore": "Ajouter Plus de Photos",
    "scan.scanMultiple": "Scanner {count} Photo{s}",
    "scan.page": "Page",
    "scan.errorTitle": "Oups, quelque chose s'est mal passé",
    "scan.tryAgain": "Réessayer",
    "scan.suggestionsTitle": "💡 Suggestions pour de meilleurs résultats:",
    "scan.suggestion1": "Assurez un bon éclairage sans ombres",
    "scan.suggestion2": "Tenez la caméra stable et directement au-dessus du menu",
    "scan.suggestion3": "Assurez-vous que le texte est net et lisible",
    "scan.suggestion4": "Photographiez le menu entier ou une partie claire",
    
    // Menu Results
    "results.title": "Résultats du Menu",
    "results.found": "{count} plats trouvés - Basé sur vos préférences et allergies",
    "results.contains": "⚠️ Contient:",
    "results.safe": "Sûr",
    "results.adjustable": "Adaptable",
    "results.containsAllergens": "Contient des Allergènes",
    "results.dishes": "plats",
    
    // Profile page
    "profile.title": "Mon Profil",
    "profile.subtitle": "Définissez vos allergies et préférences pour des correspondances personnalisées",
    "profile.businessSubtitle": "Gérez les paramètres de votre entreprise",
    "profile.allergies": "🚫 Allergies",
    "profile.allergiesDesc": "Sélectionnez toutes les allergies à prendre en compte",
    "profile.addCustom": "Ajouter une allergie personnalisée",
    "profile.customDesc": "Ajoutez une allergie non listée, y compris les ingrédients à détecter",
    "profile.allergyName": "Nom de l'allergie",
    "profile.allergyNamePlaceholder": "Ex: Sésame",
    "profile.characteristics": "Caractéristiques (séparées par des virgules)",
    "profile.characteristicsPlaceholder": "Ex: graines de sésame, huile de sésame, tahini",
    "profile.characteristicsHelp": "Ces ingrédients seront détectés sur les menus",
    "profile.addAllergy": "Ajouter Allergie",
    "profile.yourAllergies": "Vos allergies:",
    "profile.preferences": "❤️ Préférences Alimentaires",
    "profile.preferencesDesc": "Sélectionnez vos préférences alimentaires",
    "profile.save": "Enregistrer",
    "profile.saving": "Enregistrement...",
    "profile.logout": "Déconnexion",
    "profile.businessDashboard": "Tableau de Bord Entreprise",
    "profile.adminDashboard": "Tableau de Bord Admin",
    "profile.saved": "Profil enregistré! ✓",
    "profile.savedDesc": "Vos préférences ont été mises à jour.",
    "profile.savedGuestDesc": "Vos préférences ont été temporairement enregistrées.",
    
    // Auth page
    "auth.welcome": "Bienvenue sur Bite Buddy",
    "auth.subtitle": "Associez vos allergies avec des repas parfaits",
    "auth.userType": "Je suis un...",
    "auth.diner": "Convive",
    "auth.dinerDesc": "Je cherche des restaurants sûrs",
    "auth.business": "Restaurant",
    "auth.businessDesc": "J'ai un restaurant",
    "auth.signUp": "S'inscrire",
    "auth.signIn": "Se Connecter",
    "auth.continueAsGuest": "Continuer en tant qu'Invité",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.alreadyAccount": "Vous avez déjà un compte?",
    "auth.noAccount": "Pas encore de compte?",
    "auth.signUpLink": "S'inscrire",
    "auth.signInLink": "Se Connecter",
    
    // Menu View
    "menuView.title": "Menu",
    "menuView.dishesAvailable": "{count} plats disponibles",
    "menuView.noDishes": "Ce menu n'a pas encore de plats",
    "menuView.yourAllergies": "Vos allergies:",
    "menuView.compareAllergies": "Comparer avec mes allergies",
    "menuView.comparing": "Comparaison en cours...",
    "menuView.results": "Résultats:",
    "menuView.foundAllergens": "Allergènes trouvés:",
    "menuView.otherAllergensWarning": "Contient d'autres allergènes. Demandez au personnel.",
    "menuView.noDishesAdded": "Ce menu n'a pas encore de plats ajoutés.",
    "menuView.loginRequired": "Connexion requise",
    "menuView.loginRequiredDesc": "Connectez-vous pour comparer vos allergies avec le menu.",
    "menuView.loginToCompare": "Connectez-vous ou continuez en tant qu'invité pour comparer vos allergies",
    "menuView.menuNotFound": "Menu non trouvé",
    "menuView.invalidQR": "Ce code QR n'est pas valide.",
    "menuView.comparisonComplete": "Comparaison terminée!",
    "menuView.comparisonCompleteDesc": "Vos allergies ont été comparées avec le menu.",
    "menuView.errorScanning": "Erreur de scan",
    "menuView.errorLoading": "Erreur de chargement",
    "menuView.backToHome": "Retour à l'Accueil",
    
    // Business Dashboard
    "business.title": "Tableau de Bord Entreprise",
    "business.subtitle": "Consultez vos menus et statistiques de scan",
    "business.totalMenus": "Total Menus",
    "business.totalScans": "Total Scans",
    "business.uniqueAllergies": "Allergies/Préférences Uniques",
    "business.topAllergies": "Top 5 Allergies & Préférences",
    "business.topAllergiesDesc": "Allergies et préférences les plus scannées",
    "business.allAllergies": "Toutes les Allergies & Préférences",
    "business.allAllergiesDesc": "Liste complète des allergies et préférences scannées",
    "business.timesScanned": "{count}x scanné",
    "business.myMenus": "Mes Menus",
    "business.myMenusDesc": "Gérez vos menus scannés et consultez les codes QR",
    "business.noMenus": "Vous n'avez pas encore scanné de menus",
    "business.scanFirstMenu": "Scannez votre premier menu",
    "business.createdOn": "Créé le {date}",
    "business.qrCode": "Code QR: {code}",
    "business.viewQR": "Voir QR",
    "business.addNewMenu": "Ajouter Nouveau Menu",
    "business.addNewMenuDesc": "Payez 1,00€ par menu pour commencer à scanner",
    "business.payAndScan": "Payer 1,00€ et Scanner Menu",
    "business.processingPayment": "Traitement du paiement...",
    "business.noAccess": "Pas d'accès",
    "business.businessOnly": "Cette page est réservée aux entreprises.",
    "business.notLoggedIn": "Non connecté",
    "business.loginToContinue": "Connectez-vous pour continuer",
    "business.paymentError": "Erreur de paiement",
    "business.backToProfile": "Retour au Profil",
    
    // Admin Dashboard
    "admin.title": "Tableau de Bord Admin",
    "admin.subtitle": "Aperçu des statistiques de l'application",
    "admin.totalUsers": "Total Comptes",
    "admin.totalScans": "Total Scans",
    "admin.uniquePreferences": "Préférences Uniques",
    "admin.registeredUsers": "Utilisateurs enregistrés",
    "admin.menusScanned": "Menus scannés",
    "admin.differentPreferences": "Préférences différentes",
    "admin.adAnalytics": "Analytique Publicitaire",
    "admin.totalShown": "Total Affiché",
    "admin.completionRate": "Taux de Complétion",
    "admin.fullyWatched": "Entièrement Regardé",
    "admin.skipped": "Ignoré",
    "admin.avgSkipCountdown": "Compte à Rebours Moyen",
    "admin.completionVsSkip": "Complétion vs. Ignoré",
    "admin.total": "{count} total",
    "admin.completed": "Complété ({count})",
    "admin.skippedCount": "Ignoré ({count})",
    "admin.noAdAnalytics": "Pas encore d'analytique publicitaire",
    "admin.preferencesOverview": "Aperçu des Préférences",
    "admin.noPreferences": "Pas encore de préférences enregistrées",
    "admin.loadingStats": "Chargement des statistiques...",
    "admin.noAccess": "Pas d'accès",
    "admin.noAdminRights": "Vous n'avez pas les droits admin.",
    "admin.errorLoadingStats": "Impossible de charger les statistiques.",
    
    // Menu Editor
    "editor.title": "Modifier le Menu",
    "editor.subtitle": "Ajoutez des plats et spécifiez les ingrédients et allergènes",
    "editor.backToDashboard": "Retour au Tableau de Bord",
    "editor.defaultAllergens": "Allergènes par Défaut",
    "editor.defaultAllergensDesc": "Ces allergènes sont automatiquement ajoutés à tous les plats",
    "editor.addDish": "Ajouter Nouveau Plat",
    "editor.dishName": "Nom du Plat",
    "editor.dishNamePlaceholder": "Ex. Salade César",
    "editor.price": "Prix",
    "editor.description": "Description",
    "editor.descriptionPlaceholder": "Courte description du plat",
    "editor.ingredients": "Ingrédients",
    "editor.addIngredient": "Ajouter ingrédient",
    "editor.extraAllergens": "Allergènes Supplémentaires",
    "editor.addDishBtn": "Ajouter Plat",
    "editor.saving": "Enregistrement...",
    "editor.addedDishes": "Plats Ajoutés",
    "editor.finishEditing": "Terminer l'Édition",
    "editor.incomplete": "Incomplet",
    "editor.incompleteDesc": "Entrez au moins un nom et des ingrédients",
    "editor.dishAdded": "Plat ajouté!",
    "editor.dishAddedDesc": "{name} a été ajouté au menu",
    "editor.loadError": "Erreur de chargement",
    "editor.saveError": "Erreur d'enregistrement",
    
    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.back": "Retour",
    "common.close": "Fermer",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.add": "Ajouter",
    "common.login": "Se Connecter",
    "common.continueAsGuest": "Continuer en tant qu'Invité",
  },
  es: {
    // Index page
    "index.title": "Encuentra tu comida perfecta",
    "index.subtitle": "Combina tus alergias y preferencias con restaurantes",
    "index.scanMenu": "Escanear Menú",
    "index.myProfile": "Mi Perfil",
    "index.signIn": "Iniciar Sesión",
    "index.feature1Title": "Escanear y Reconocer",
    "index.feature1Desc": "Escanea menús con tu cámara y deja que la IA analice los ingredientes",
    "index.feature2Title": "Seguridad Primero",
    "index.feature2Desc": "Recibe advertencias claras para tus alergias específicas",
    "index.feature3Title": "Personal",
    "index.feature3Desc": "Guarda tus alergias y preferencias para verificaciones más rápidas",
    "index.howItWorksTitle": "Cómo funciona",
    "index.howItWorksDesc": "Cena segura en 3 simples pasos",
    "index.step1Title": "Configura tus preferencias",
    "index.step1Desc": "Agrega tus alergias y preferencias a tu perfil. Solo tienes que hacerlo una vez.",
    "index.step2Title": "Escanea el menú",
    "index.step2Desc": "Usa tu cámara para escanear el menú. Nuestra IA hace el resto.",
    "index.step3Title": "Ve qué es seguro",
    "index.step3Desc": "Cada plato recibe un emoji: 😊 seguro, 😐 adaptable, o 🤢 contiene alérgenos.",
    "index.readyTitle": "¿Listo para disfrutar con seguridad?",
    "index.readyDesc": "Empieza a escanear y descubre comidas seguras",
    
    // Allergies
    "allergy.noten": "Frutos secos",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Lactosa",
    "allergy.schaaldieren": "Mariscos",
    "allergy.vis": "Pescado",
    "allergy.eieren": "Huevos",
    "allergy.soja": "Soja",
    "allergy.sulfiet": "Sulfitos",
    
    // Preferences
    "preference.vegetarisch": "Vegetariano",
    "preference.veganistisch": "Vegano",
    "preference.halal": "Halal",
    "preference.kosher": "Kosher",
    
    // Scan page
    "scan.title": "Escanear Menú",
    "scan.subtitle": "Elige cómo subir el menú",
    "scan.camera": "Cámara",
    "scan.cameraDesc": "Escanea directamente con tu cámara",
    "scan.upload": "Subir",
    "scan.uploadDesc": "Sube una foto o PDF",
    "scan.multiple": "Múltiples Fotos",
    "scan.multipleDesc": "Combina diferentes páginas",
    "scan.analyzing": "Analizando...",
    "scan.analyzingDesc": "La IA está analizando tu menú. Esto puede tomar un momento.",
    "scan.analyzingMultiple": "La IA está analizando {count} foto{s}. Esto puede tomar un momento.",
    "scan.checkPhoto": "Verifica tu foto",
    "scan.readable": "¿El menú es claramente legible?",
    "scan.retry": "Reintentar",
    "scan.scanButton": "Escanear",
    "scan.back": "Volver",
    "scan.tipsTitle": "💡 Consejos para mejores resultados:",
    "scan.tip1": "Asegura buena iluminación",
    "scan.tip2": "Mantén la cámara estable",
    "scan.tip3": "Asegúrate de que el texto sea legible",
    "scan.makePhoto": "Tomar una foto",
    "scan.position": "Posiciona el menú en el encuadre",
    "scan.cancel": "Cancelar",
    "scan.takePhoto": "Tomar Foto",
    "scan.multipleTitle": "Múltiples Fotos",
    "scan.photosAdded": "{count} foto{s} añadida{s}",
    "scan.addPhotos": "Añade fotos de diferentes páginas del menú",
    "scan.addMore": "Añadir Más Fotos",
    "scan.scanMultiple": "Escanear {count} Foto{s}",
    "scan.page": "Página",
    "scan.errorTitle": "Ups, algo salió mal",
    "scan.tryAgain": "Intentar de Nuevo",
    "scan.suggestionsTitle": "💡 Sugerencias para mejores resultados:",
    "scan.suggestion1": "Asegura buena iluminación sin sombras",
    "scan.suggestion2": "Mantén la cámara estable y directamente sobre el menú",
    "scan.suggestion3": "Asegúrate de que el texto esté nítido y legible",
    "scan.suggestion4": "Fotografía el menú completo o una parte clara",
    
    // Menu Results
    "results.title": "Resultados del Menú",
    "results.found": "{count} platos encontrados - Basado en tus preferencias y alergias",
    "results.contains": "⚠️ Contiene:",
    "results.safe": "Seguro",
    "results.adjustable": "Adaptable",
    "results.containsAllergens": "Contiene Alérgenos",
    "results.dishes": "platos",
    
    // Profile page
    "profile.title": "Mi Perfil",
    "profile.subtitle": "Configura tus alergias y preferencias para coincidencias personalizadas",
    "profile.businessSubtitle": "Gestiona la configuración de tu negocio",
    "profile.allergies": "🚫 Alergias",
    "profile.allergiesDesc": "Selecciona todas las alergias a considerar",
    "profile.addCustom": "Añadir alergia personalizada",
    "profile.customDesc": "Añade una alergia no listada, incluyendo ingredientes a detectar",
    "profile.allergyName": "Nombre de la alergia",
    "profile.allergyNamePlaceholder": "Ej: Sésamo",
    "profile.characteristics": "Características (separadas por comas)",
    "profile.characteristicsPlaceholder": "Ej: semillas de sésamo, aceite de sésamo, tahini",
    "profile.characteristicsHelp": "Estos ingredientes serán detectados en los menús",
    "profile.addAllergy": "Añadir Alergia",
    "profile.yourAllergies": "Tus alergias:",
    "profile.preferences": "❤️ Preferencias Dietéticas",
    "profile.preferencesDesc": "Selecciona tus preferencias dietéticas",
    "profile.save": "Guardar",
    "profile.saving": "Guardando...",
    "profile.logout": "Cerrar Sesión",
    "profile.businessDashboard": "Panel de Negocio",
    "profile.adminDashboard": "Panel de Admin",
    "profile.saved": "¡Perfil guardado! ✓",
    "profile.savedDesc": "Tus preferencias han sido actualizadas.",
    "profile.savedGuestDesc": "Tus preferencias han sido guardadas temporalmente.",
    
    // Auth page
    "auth.welcome": "Bienvenido a Bite Buddy",
    "auth.subtitle": "Combina tus alergias con comidas perfectas",
    "auth.userType": "Soy un...",
    "auth.diner": "Comensal",
    "auth.dinerDesc": "Busco restaurantes seguros",
    "auth.business": "Restaurante",
    "auth.businessDesc": "Tengo un restaurante",
    "auth.signUp": "Registrarse",
    "auth.signIn": "Iniciar Sesión",
    "auth.continueAsGuest": "Continuar como Invitado",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.alreadyAccount": "¿Ya tienes cuenta?",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.signUpLink": "Registrarse",
    "auth.signInLink": "Iniciar Sesión",
    
    // Menu View
    "menuView.title": "Menú",
    "menuView.dishesAvailable": "{count} platos disponibles",
    "menuView.noDishes": "Este menú aún no tiene platos",
    "menuView.yourAllergies": "Tus alergias:",
    "menuView.compareAllergies": "Comparar con mis alergias",
    "menuView.comparing": "Comparando...",
    "menuView.results": "Resultados:",
    "menuView.foundAllergens": "Alérgenos encontrados:",
    "menuView.otherAllergensWarning": "Contiene otros alérgenos. Pregunta al personal.",
    "menuView.noDishesAdded": "Este menú aún no tiene platos añadidos.",
    "menuView.loginRequired": "Inicio de sesión requerido",
    "menuView.loginRequiredDesc": "Inicia sesión para comparar tus alergias con el menú.",
    "menuView.loginToCompare": "Inicia sesión o continúa como invitado para comparar tus alergias",
    "menuView.menuNotFound": "Menú no encontrado",
    "menuView.invalidQR": "Este código QR no es válido.",
    "menuView.comparisonComplete": "¡Comparación completa!",
    "menuView.comparisonCompleteDesc": "Tus alergias han sido comparadas con el menú.",
    "menuView.errorScanning": "Error al escanear",
    "menuView.errorLoading": "Error al cargar",
    "menuView.backToHome": "Volver al Inicio",
    
    // Business Dashboard
    "business.title": "Panel de Negocio",
    "business.subtitle": "Ve tus menús y estadísticas de escaneo",
    "business.totalMenus": "Total Menús",
    "business.totalScans": "Total Escaneos",
    "business.uniqueAllergies": "Alergias/Preferencias Únicas",
    "business.topAllergies": "Top 5 Alergias y Preferencias",
    "business.topAllergiesDesc": "Alergias y preferencias más escaneadas",
    "business.allAllergies": "Todas las Alergias y Preferencias",
    "business.allAllergiesDesc": "Lista completa de alergias y preferencias escaneadas",
    "business.timesScanned": "{count}x escaneado",
    "business.myMenus": "Mis Menús",
    "business.myMenusDesc": "Gestiona tus menús escaneados y ve los códigos QR",
    "business.noMenus": "Aún no has escaneado ningún menú",
    "business.scanFirstMenu": "Escanea tu primer menú",
    "business.createdOn": "Creado el {date}",
    "business.qrCode": "Código QR: {code}",
    "business.viewQR": "Ver QR",
    "business.addNewMenu": "Añadir Nuevo Menú",
    "business.addNewMenuDesc": "Paga 1,00€ por menú para empezar a escanear",
    "business.payAndScan": "Pagar 1,00€ y Escanear Menú",
    "business.processingPayment": "Procesando pago...",
    "business.noAccess": "Sin acceso",
    "business.businessOnly": "Esta página es solo para negocios.",
    "business.notLoggedIn": "No conectado",
    "business.loginToContinue": "Inicia sesión para continuar",
    "business.paymentError": "Error de pago",
    "business.backToProfile": "Volver al Perfil",
    
    // Admin Dashboard
    "admin.title": "Panel de Admin",
    "admin.subtitle": "Resumen de estadísticas de la app",
    "admin.totalUsers": "Total Cuentas",
    "admin.totalScans": "Total Escaneos",
    "admin.uniquePreferences": "Preferencias Únicas",
    "admin.registeredUsers": "Usuarios registrados",
    "admin.menusScanned": "Menús escaneados",
    "admin.differentPreferences": "Preferencias diferentes",
    "admin.adAnalytics": "Analítica de Anuncios",
    "admin.totalShown": "Total Mostrado",
    "admin.completionRate": "Tasa de Completado",
    "admin.fullyWatched": "Completamente Visto",
    "admin.skipped": "Saltado",
    "admin.avgSkipCountdown": "Cuenta Regresiva Promedio",
    "admin.completionVsSkip": "Completado vs. Saltado",
    "admin.total": "{count} total",
    "admin.completed": "Completado ({count})",
    "admin.skippedCount": "Saltado ({count})",
    "admin.noAdAnalytics": "Aún no hay analítica de anuncios",
    "admin.preferencesOverview": "Resumen de Preferencias",
    "admin.noPreferences": "Aún no hay preferencias registradas",
    "admin.loadingStats": "Cargando estadísticas...",
    "admin.noAccess": "Sin acceso",
    "admin.noAdminRights": "No tienes derechos de admin.",
    "admin.errorLoadingStats": "No se pudieron cargar las estadísticas.",
    
    // Menu Editor
    "editor.title": "Editar Menú",
    "editor.subtitle": "Añade platos y especifica ingredientes y alérgenos",
    "editor.backToDashboard": "Volver al Panel",
    "editor.defaultAllergens": "Alérgenos por Defecto",
    "editor.defaultAllergensDesc": "Estos alérgenos se añaden automáticamente a todos los platos",
    "editor.addDish": "Añadir Nuevo Plato",
    "editor.dishName": "Nombre del Plato",
    "editor.dishNamePlaceholder": "Ej. Ensalada César",
    "editor.price": "Precio",
    "editor.description": "Descripción",
    "editor.descriptionPlaceholder": "Breve descripción del plato",
    "editor.ingredients": "Ingredientes",
    "editor.addIngredient": "Añadir ingrediente",
    "editor.extraAllergens": "Alérgenos Adicionales",
    "editor.addDishBtn": "Añadir Plato",
    "editor.saving": "Guardando...",
    "editor.addedDishes": "Platos Añadidos",
    "editor.finishEditing": "Terminar Edición",
    "editor.incomplete": "Incompleto",
    "editor.incompleteDesc": "Introduce al menos un nombre e ingredientes",
    "editor.dishAdded": "¡Plato añadido!",
    "editor.dishAddedDesc": "{name} ha sido añadido al menú",
    "editor.loadError": "Error al cargar",
    "editor.saveError": "Error al guardar",
    
    // Common
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.back": "Volver",
    "common.close": "Cerrar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.add": "Añadir",
    "common.login": "Iniciar Sesión",
    "common.continueAsGuest": "Continuar como Invitado",
  },
  de: {
    // Index page
    "index.title": "Finde deine perfekte Mahlzeit",
    "index.subtitle": "Verbinde deine Allergien und Vorlieben mit Restaurants",
    "index.scanMenu": "Menü Scannen",
    "index.myProfile": "Mein Profil",
    "index.signIn": "Anmelden",
    "index.feature1Title": "Scannen & Erkennen",
    "index.feature1Desc": "Scannen Sie Menüs mit Ihrer Kamera und lassen Sie KI die Zutaten analysieren",
    "index.feature2Title": "Sicherheit Zuerst",
    "index.feature2Desc": "Erhalten Sie klare Warnungen für Ihre spezifischen Allergien",
    "index.feature3Title": "Persönlich",
    "index.feature3Desc": "Speichern Sie Ihre Allergien und Vorlieben für schnellere Überprüfungen",
    "index.howItWorksTitle": "So funktioniert es",
    "index.howItWorksDesc": "Sicheres Essen in 3 einfachen Schritten",
    "index.step1Title": "Lege deine Präferenzen fest",
    "index.step1Desc": "Fügen Sie Ihre Allergien und Vorlieben zu Ihrem Profil hinzu. Sie müssen dies nur einmal tun.",
    "index.step2Title": "Scannen Sie das Menü",
    "index.step2Desc": "Verwenden Sie Ihre Kamera, um das Menü zu scannen. Unsere KI erledigt den Rest.",
    "index.step3Title": "Sehen Sie sofort, was sicher ist",
    "index.step3Desc": "Jedes Gericht bekommt ein Smiley: 😊 sicher, 😐 anpassbar, oder 🤢 enthält Allergene.",
    "index.readyTitle": "Bereit, sicher zu genießen?",
    "index.readyDesc": "Starten Sie jetzt mit dem Scannen und entdecken Sie sichere Mahlzeiten",
    
    // Allergies
    "allergy.noten": "Nüsse",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Laktose",
    "allergy.schaaldieren": "Schalentiere",
    "allergy.vis": "Fisch",
    "allergy.eieren": "Eier",
    "allergy.soja": "Soja",
    "allergy.sulfiet": "Sulfite",
    
    // Preferences
    "preference.vegetarisch": "Vegetarisch",
    "preference.veganistisch": "Vegan",
    "preference.halal": "Halal",
    "preference.kosher": "Koscher",
    
    // Scan page
    "scan.title": "Menü Scannen",
    "scan.subtitle": "Wählen Sie, wie Sie das Menü hochladen möchten",
    "scan.camera": "Kamera",
    "scan.cameraDesc": "Scannen Sie direkt mit Ihrer Kamera",
    "scan.upload": "Hochladen",
    "scan.uploadDesc": "Laden Sie ein Foto oder PDF hoch",
    "scan.multiple": "Mehrere Fotos",
    "scan.multipleDesc": "Kombinieren Sie verschiedene Seiten",
    "scan.analyzing": "Analysiere...",
    "scan.analyzingDesc": "Die KI analysiert Ihr Menü. Dies kann einen Moment dauern.",
    "scan.analyzingMultiple": "Die KI analysiert {count} Foto{s}. Dies kann einen Moment dauern.",
    "scan.checkPhoto": "Überprüfen Sie Ihr Foto",
    "scan.readable": "Ist das Menü gut lesbar?",
    "scan.retry": "Erneut versuchen",
    "scan.scanButton": "Scannen",
    "scan.back": "Zurück",
    "scan.tipsTitle": "💡 Tipps für beste Ergebnisse:",
    "scan.tip1": "Sorgen Sie für gute Beleuchtung",
    "scan.tip2": "Halten Sie die Kamera ruhig",
    "scan.tip3": "Stellen Sie sicher, dass der Text lesbar ist",
    "scan.makePhoto": "Foto aufnehmen",
    "scan.position": "Positionieren Sie das Menü im Bild",
    "scan.cancel": "Abbrechen",
    "scan.takePhoto": "Foto Aufnehmen",
    "scan.multipleTitle": "Mehrere Fotos",
    "scan.photosAdded": "{count} Foto{s} hinzugefügt",
    "scan.addPhotos": "Fügen Sie Fotos verschiedener Menüseiten hinzu",
    "scan.addMore": "Mehr Fotos Hinzufügen",
    "scan.scanMultiple": "{count} Foto{s} Scannen",
    "scan.page": "Seite",
    "scan.errorTitle": "Ups, etwas ist schiefgelaufen",
    "scan.tryAgain": "Erneut Versuchen",
    "scan.suggestionsTitle": "💡 Vorschläge für bessere Ergebnisse:",
    "scan.suggestion1": "Sorgen Sie für gute Beleuchtung ohne Schatten",
    "scan.suggestion2": "Halten Sie die Kamera ruhig und direkt über dem Menü",
    "scan.suggestion3": "Stellen Sie sicher, dass der Text scharf und lesbar ist",
    "scan.suggestion4": "Fotografieren Sie das gesamte Menü oder einen klaren Teil davon",
    
    // Menu Results
    "results.title": "Menü Ergebnisse",
    "results.found": "{count} Gerichte gefunden - Basierend auf Ihren Vorlieben und Allergien",
    "results.contains": "⚠️ Enthält:",
    "results.safe": "Sicher",
    "results.adjustable": "Anpassbar",
    "results.containsAllergens": "Enthält Allergene",
    "results.dishes": "Gerichte",
    
    // Profile page
    "profile.title": "Mein Profil",
    "profile.subtitle": "Stellen Sie Ihre Allergien und Vorlieben für personalisierte Übereinstimmungen ein",
    "profile.businessSubtitle": "Verwalten Sie Ihre Geschäftseinstellungen",
    "profile.allergies": "🚫 Allergien",
    "profile.allergiesDesc": "Wählen Sie alle Allergien aus, die berücksichtigt werden sollen",
    "profile.addCustom": "Eigene Allergie hinzufügen",
    "profile.customDesc": "Fügen Sie eine nicht gelistete Allergie hinzu, einschließlich zu erkennender Zutaten",
    "profile.allergyName": "Allergiename",
    "profile.allergyNamePlaceholder": "Z.B.: Sesam",
    "profile.characteristics": "Merkmale (durch Kommas getrennt)",
    "profile.characteristicsPlaceholder": "Z.B.: Sesamsamen, Sesamöl, Tahini",
    "profile.characteristicsHelp": "Diese Zutaten werden auf Menüs erkannt",
    "profile.addAllergy": "Allergie Hinzufügen",
    "profile.yourAllergies": "Ihre Allergien:",
    "profile.preferences": "❤️ Ernährungspräferenzen",
    "profile.preferencesDesc": "Wählen Sie Ihre Ernährungspräferenzen",
    "profile.save": "Speichern",
    "profile.saving": "Speichern...",
    "profile.logout": "Abmelden",
    "profile.businessDashboard": "Geschäfts-Dashboard",
    "profile.adminDashboard": "Admin-Dashboard",
    "profile.saved": "Profil gespeichert! ✓",
    "profile.savedDesc": "Ihre Vorlieben wurden aktualisiert.",
    "profile.savedGuestDesc": "Ihre Vorlieben wurden temporär gespeichert.",
    
    // Auth page
    "auth.welcome": "Willkommen bei Bite Buddy",
    "auth.subtitle": "Verbinden Sie Ihre Allergien mit perfekten Mahlzeiten",
    "auth.userType": "Ich bin ein...",
    "auth.diner": "Gast",
    "auth.dinerDesc": "Ich suche sichere Restaurants",
    "auth.business": "Restaurant",
    "auth.businessDesc": "Ich habe ein Restaurant",
    "auth.signUp": "Registrieren",
    "auth.signIn": "Anmelden",
    "auth.continueAsGuest": "Als Gast Fortfahren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.alreadyAccount": "Haben Sie bereits ein Konto?",
    "auth.noAccount": "Noch kein Konto?",
    "auth.signUpLink": "Registrieren",
    "auth.signInLink": "Anmelden",
    
    // Menu View
    "menuView.title": "Menü",
    "menuView.dishesAvailable": "{count} Gerichte verfügbar",
    "menuView.noDishes": "Dieses Menü hat noch keine Gerichte",
    "menuView.yourAllergies": "Ihre Allergien:",
    "menuView.compareAllergies": "Mit meinen Allergien vergleichen",
    "menuView.comparing": "Vergleiche...",
    "menuView.results": "Ergebnisse:",
    "menuView.foundAllergens": "Gefundene Allergene:",
    "menuView.otherAllergensWarning": "Enthält andere Allergene. Fragen Sie das Personal.",
    "menuView.noDishesAdded": "Diesem Menü wurden noch keine Gerichte hinzugefügt.",
    "menuView.loginRequired": "Anmeldung erforderlich",
    "menuView.loginRequiredDesc": "Melden Sie sich an, um Ihre Allergien mit dem Menü zu vergleichen.",
    "menuView.loginToCompare": "Melden Sie sich an oder fahren Sie als Gast fort, um Ihre Allergien zu vergleichen",
    "menuView.menuNotFound": "Menü nicht gefunden",
    "menuView.invalidQR": "Dieser QR-Code ist ungültig.",
    "menuView.comparisonComplete": "Vergleich abgeschlossen!",
    "menuView.comparisonCompleteDesc": "Ihre Allergien wurden mit dem Menü verglichen.",
    "menuView.errorScanning": "Fehler beim Scannen",
    "menuView.errorLoading": "Fehler beim Laden",
    "menuView.backToHome": "Zurück zur Startseite",
    
    // Business Dashboard
    "business.title": "Geschäfts-Dashboard",
    "business.subtitle": "Sehen Sie Ihre Menüs und Scan-Statistiken",
    "business.totalMenus": "Gesamt Menüs",
    "business.totalScans": "Gesamt Scans",
    "business.uniqueAllergies": "Einzigartige Allergien/Vorlieben",
    "business.topAllergies": "Top 5 Allergien & Vorlieben",
    "business.topAllergiesDesc": "Am häufigsten gescannte Allergien und Vorlieben",
    "business.allAllergies": "Alle Allergien & Vorlieben",
    "business.allAllergiesDesc": "Vollständige Liste der gescannten Allergien und Vorlieben",
    "business.timesScanned": "{count}x gescannt",
    "business.myMenus": "Meine Menüs",
    "business.myMenusDesc": "Verwalten Sie Ihre gescannten Menüs und sehen Sie QR-Codes",
    "business.noMenus": "Sie haben noch keine Menüs gescannt",
    "business.scanFirstMenu": "Scannen Sie Ihr erstes Menü",
    "business.createdOn": "Erstellt am {date}",
    "business.qrCode": "QR-Code: {code}",
    "business.viewQR": "QR Anzeigen",
    "business.addNewMenu": "Neues Menü Hinzufügen",
    "business.addNewMenuDesc": "Zahlen Sie 1,00€ pro Menü, um mit dem Scannen zu beginnen",
    "business.payAndScan": "1,00€ Zahlen und Menü Scannen",
    "business.processingPayment": "Zahlung wird verarbeitet...",
    "business.noAccess": "Kein Zugang",
    "business.businessOnly": "Diese Seite ist nur für Geschäfte.",
    "business.notLoggedIn": "Nicht angemeldet",
    "business.loginToContinue": "Melden Sie sich an, um fortzufahren",
    "business.paymentError": "Zahlungsfehler",
    "business.backToProfile": "Zurück zum Profil",
    
    // Admin Dashboard
    "admin.title": "Admin-Dashboard",
    "admin.subtitle": "Übersicht der App-Statistiken",
    "admin.totalUsers": "Gesamt Konten",
    "admin.totalScans": "Gesamt Scans",
    "admin.uniquePreferences": "Einzigartige Vorlieben",
    "admin.registeredUsers": "Registrierte Benutzer",
    "admin.menusScanned": "Gescannte Menüs",
    "admin.differentPreferences": "Verschiedene Vorlieben",
    "admin.adAnalytics": "Werbe-Analytics",
    "admin.totalShown": "Gesamt Angezeigt",
    "admin.completionRate": "Abschlussrate",
    "admin.fullyWatched": "Vollständig Angesehen",
    "admin.skipped": "Übersprungen",
    "admin.avgSkipCountdown": "Durchschn. Skip-Countdown",
    "admin.completionVsSkip": "Abschluss vs. Übersprungen",
    "admin.total": "{count} gesamt",
    "admin.completed": "Abgeschlossen ({count})",
    "admin.skippedCount": "Übersprungen ({count})",
    "admin.noAdAnalytics": "Noch keine Werbe-Analytics verfügbar",
    "admin.preferencesOverview": "Vorlieben-Übersicht",
    "admin.noPreferences": "Noch keine Vorlieben registriert",
    "admin.loadingStats": "Statistiken werden geladen...",
    "admin.noAccess": "Kein Zugang",
    "admin.noAdminRights": "Sie haben keine Admin-Rechte.",
    "admin.errorLoadingStats": "Statistiken konnten nicht geladen werden.",
    
    // Menu Editor
    "editor.title": "Menü Bearbeiten",
    "editor.subtitle": "Fügen Sie Gerichte hinzu und spezifizieren Sie Zutaten und Allergene",
    "editor.backToDashboard": "Zurück zum Dashboard",
    "editor.defaultAllergens": "Standard-Allergene",
    "editor.defaultAllergensDesc": "Diese Allergene werden automatisch allen Gerichten hinzugefügt",
    "editor.addDish": "Neues Gericht Hinzufügen",
    "editor.dishName": "Gerichtname",
    "editor.dishNamePlaceholder": "Z.B. Caesar Salat",
    "editor.price": "Preis",
    "editor.description": "Beschreibung",
    "editor.descriptionPlaceholder": "Kurze Beschreibung des Gerichts",
    "editor.ingredients": "Zutaten",
    "editor.addIngredient": "Zutat hinzufügen",
    "editor.extraAllergens": "Zusätzliche Allergene",
    "editor.addDishBtn": "Gericht Hinzufügen",
    "editor.saving": "Speichern...",
    "editor.addedDishes": "Hinzugefügte Gerichte",
    "editor.finishEditing": "Bearbeitung Beenden",
    "editor.incomplete": "Unvollständig",
    "editor.incompleteDesc": "Geben Sie mindestens einen Namen und Zutaten ein",
    "editor.dishAdded": "Gericht hinzugefügt!",
    "editor.dishAddedDesc": "{name} wurde dem Menü hinzugefügt",
    "editor.loadError": "Fehler beim Laden",
    "editor.saveError": "Fehler beim Speichern",
    
    // Common
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.back": "Zurück",
    "common.close": "Schließen",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.add": "Hinzufügen",
    "common.login": "Anmelden",
    "common.continueAsGuest": "Als Gast Fortfahren",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "en" || saved === "nl" || saved === "fr" || saved === "es" || saved === "de") ? saved : "nl";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || translations["nl"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
