import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "nl" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Index page
    "index.title": "Vind je perfecte maaltijd",
    "index.subtitle": "Match je allergieën en voorkeuren met restaurants",
    "index.scanMenu": "Scan Menu",
    "index.myProfile": "Mijn Profiel",
    "index.signIn": "Inloggen",
    "index.feature1Title": "Scan & Herken",
    "index.feature1Desc": "Scan menukaarten direct met je camera en laat AI de ingrediënten analyseren",
    "index.feature2Title": "Veiligheid Eerst",
    "index.feature2Desc": "Krijg direct duidelijke waarschuwingen voor jouw specifieke allergieën",
    "index.feature3Title": "Persoonlijk",
    "index.feature3Desc": "Sla je allergieën en voorkeuren op voor snellere controles",
    "index.howItWorksTitle": "Zo werkt het",
    "index.howItWorksDesc": "Veilig dineren in 3 simpele stappen",
    "index.step1Title": "Stel je voorkeuren in",
    "index.step1Desc": "Voeg je allergieën, dieetwensen en voorkeuren toe aan je profiel. Dit hoef je maar één keer te doen.",
    "index.step2Title": "Scan de menukaart",
    "index.step2Desc": "Gebruik je camera om de menukaart te scannen, of upload een foto. Onze AI doet de rest.",
    "index.step3Title": "Zie direct wat veilig is",
    "index.step3Desc": "Elk gerecht krijgt een smiley: 😊 veilig, 😐 aanpasbaar, of 🤢 bevat allergenen.",
    "index.readyTitle": "Klaar om veilig te genieten?",
    "index.readyDesc": "Begin nu met scannen en ontdek veilige maaltijden",
    
    // Allergies
    "allergy.noten": "Noten",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Lactose",
    "allergy.schaaldieren": "Schaaldieren",
    "allergy.vis": "Vis",
    "allergy.eieren": "Eieren",
    "allergy.soja": "Soja",
    "allergy.sulfiet": "Sulfiet",
    
    // Preferences
    "preference.vegetarisch": "Vegetarisch",
    "preference.veganistisch": "Veganistisch",
    "preference.halal": "Halal",
    "preference.kosher": "Kosher",
    
    // Scan page
    "scan.title": "Menu Scannen",
    "scan.subtitle": "Kies hoe je de menukaart wilt uploaden",
    "scan.camera": "Camera",
    "scan.cameraDesc": "Scan direct met je camera",
    "scan.upload": "Upload",
    "scan.uploadDesc": "Upload een foto of PDF",
    "scan.multiple": "Meerdere Foto's",
    "scan.multipleDesc": "Combineer verschillende pagina's",
    "scan.analyzing": "Analyseren...",
    "scan.analyzingDesc": "De AI analyseert je menu. Dit kan even duren.",
    "scan.analyzingMultiple": "De AI analyseert {count} foto{s}. Dit kan even duren.",
    "scan.checkPhoto": "Controleer je foto",
    "scan.readable": "Is de menukaart goed leesbaar?",
    "scan.retry": "Opnieuw",
    "scan.scanButton": "Scannen",
    "scan.back": "Terug",
    "scan.tipsTitle": "💡 Tips voor beste resultaten:",
    "scan.tip1": "Zorg voor goede verlichting",
    "scan.tip2": "Houd de camera stabiel",
    "scan.tip3": "Zorg dat de tekst goed leesbaar is",
    "scan.makePhoto": "Maak een foto",
    "scan.position": "Positioneer de menukaart in beeld",
    "scan.cancel": "Annuleren",
    "scan.takePhoto": "Foto Maken",
    "scan.multipleTitle": "Meerdere Foto's",
    "scan.photosAdded": "{count} foto{s} toegevoegd",
    "scan.addPhotos": "Voeg foto's van verschillende menupagina's toe",
    "scan.addMore": "Meer Foto's Toevoegen",
    "scan.scanMultiple": "Scan {count} Foto{s}",
    "scan.page": "Pagina",
    "scan.errorTitle": "Oeps, dat ging niet goed",
    "scan.tryAgain": "Probeer Opnieuw",
    "scan.suggestionsTitle": "💡 Suggesties voor betere resultaten:",
    "scan.suggestion1": "Zorg voor goede verlichting zonder schaduwen",
    "scan.suggestion2": "Houd de camera stabiel en recht boven het menu",
    "scan.suggestion3": "Zorg dat de tekst scherp en goed leesbaar is",
    "scan.suggestion4": "Fotografeer het hele menu of een duidelijk deel ervan",
    
    // Menu Results
    "results.title": "Menu Resultaten",
    "results.found": "{count} gerechten gevonden - Gebaseerd op jouw voorkeuren en allergieën",
    "results.contains": "⚠️ Bevat:",
    "results.safe": "Veilig",
    "results.adjustable": "Aanpasbaar",
    "results.containsAllergens": "Bevat Allergenen",
    "results.dishes": "gerechten",
    
    // Profile page
    "profile.title": "Mijn Profiel",
    "profile.subtitle": "Stel je allergieën en voorkeuren in voor gepersonaliseerde matches",
    "profile.businessSubtitle": "Beheer je bedrijfsinstellingen",
    "profile.allergies": "🚫 Allergieën",
    "profile.allergiesDesc": "Selecteer alle allergieën waar we rekening mee moeten houden",
    "profile.addCustom": "Eigen allergie toevoegen",
    "profile.customDesc": "Voeg een allergie toe die niet in de lijst staat, inclusief ingrediënten die we moeten detecteren",
    "profile.allergyName": "Allergie naam",
    "profile.allergyNamePlaceholder": "Bijv: Sesam",
    "profile.characteristics": "Kenmerken (gescheiden door komma's)",
    "profile.characteristicsPlaceholder": "Bijv: sesamzaad, sesam olie, tahini",
    "profile.characteristicsHelp": "Deze ingrediënten worden gedetecteerd op menukaarten",
    "profile.addAllergy": "Allergie Toevoegen",
    "profile.yourAllergies": "Jouw allergieën:",
    "profile.preferences": "❤️ Dieetvoorkeuren",
    "profile.preferencesDesc": "Selecteer je dieetwensen",
    "profile.save": "Opslaan",
    "profile.saving": "Opslaan...",
    "profile.logout": "Uitloggen",
    "profile.businessDashboard": "Bedrijf Dashboard",
    "profile.adminDashboard": "Admin Dashboard",
    "profile.saved": "Profiel opgeslagen! ✓",
    "profile.savedDesc": "Je voorkeuren zijn succesvol bijgewerkt.",
    "profile.savedGuestDesc": "Je voorkeuren zijn tijdelijk opgeslagen.",
    
    // Auth page
    "auth.welcome": "Welkom bij Bite Buddy",
    "auth.subtitle": "Match je allergieën met perfecte maaltijden",
    "auth.userType": "Ik ben een...",
    "auth.diner": "Eter",
    "auth.dinerDesc": "Ik zoek veilige restaurants",
    "auth.business": "Eetgever",
    "auth.businessDesc": "Ik heb een restaurant",
    "auth.signUp": "Aanmelden",
    "auth.signIn": "Inloggen",
    "auth.continueAsGuest": "Doorgaan als Gast",
    "auth.email": "Email",
    "auth.password": "Wachtwoord",
    "auth.alreadyAccount": "Heb je al een account?",
    "auth.noAccount": "Nog geen account?",
    "auth.signUpLink": "Aanmelden",
    "auth.signInLink": "Inloggen",
    
    // Menu View
    "menuView.title": "Menu",
    "menuView.dishesAvailable": "{count} gerechten beschikbaar",
    "menuView.noDishes": "Dit menu heeft nog geen gerechten",
    "menuView.yourAllergies": "Je allergieën:",
    "menuView.compareAllergies": "Vergelijk met mijn allergieën",
    "menuView.comparing": "Bezig met vergelijken...",
    "menuView.results": "Resultaten:",
    "menuView.foundAllergens": "Gevonden allergenen:",
    "menuView.otherAllergensWarning": "Bevat andere allergenen. Vraag personeel om aanpassingen.",
    "menuView.noDishesAdded": "Dit menu heeft nog geen gerechten toegevoegd.",
    "menuView.loginRequired": "Inloggen vereist",
    "menuView.loginRequiredDesc": "Log in om je allergieën te vergelijken met het menu.",
    "menuView.loginToCompare": "Log in of ga door als gast om je allergieën te vergelijken met dit menu",
    "menuView.menuNotFound": "Menu niet gevonden",
    "menuView.invalidQR": "Deze QR-code is niet geldig.",
    "menuView.comparisonComplete": "Vergelijking compleet!",
    "menuView.comparisonCompleteDesc": "Je allergieën zijn vergeleken met het menu.",
    "menuView.errorScanning": "Fout bij scannen",
    "menuView.errorLoading": "Fout bij laden",
    "menuView.backToHome": "Terug naar Home",
    
    // Business Dashboard
    "business.title": "Bedrijf Dashboard",
    "business.subtitle": "Bekijk je menu's en scan statistieken",
    "business.totalMenus": "Totaal Menu's",
    "business.totalScans": "Totaal Scans",
    "business.uniqueAllergies": "Unieke Allergieën/Voorkeuren",
    "business.topAllergies": "Top 5 Allergieën & Voorkeuren",
    "business.topAllergiesDesc": "Meest gescande allergieën en voorkeuren",
    "business.allAllergies": "Alle Allergieën & Voorkeuren",
    "business.allAllergiesDesc": "Volledige lijst van gescande allergieën en voorkeuren",
    "business.timesScanned": "{count}x gescand",
    "business.myMenus": "Mijn Menu's",
    "business.myMenusDesc": "Beheer je gescande menu's en bekijk QR-codes",
    "business.noMenus": "Je hebt nog geen menu's gescand",
    "business.scanFirstMenu": "Scan je eerste menu",
    "business.createdOn": "Gemaakt op {date}",
    "business.qrCode": "QR Code: {code}",
    "business.viewQR": "Bekijk QR",
    "business.addNewMenu": "Nieuw Menu Toevoegen",
    "business.addNewMenuDesc": "Betaal €1,00 per menu om te beginnen met scannen",
    "business.payAndScan": "Betaal €1,00 en Scan Menu",
    "business.processingPayment": "Bezig met betaling...",
    "business.noAccess": "Geen toegang",
    "business.businessOnly": "Deze pagina is alleen voor bedrijven.",
    "business.notLoggedIn": "Niet ingelogd",
    "business.loginToContinue": "Log in om door te gaan",
    "business.paymentError": "Fout bij betaling",
    "business.backToProfile": "Terug naar Profiel",
    
    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Overzicht van app statistieken",
    "admin.totalUsers": "Totaal Accounts",
    "admin.totalScans": "Totaal Scans",
    "admin.uniquePreferences": "Unieke Voorkeuren",
    "admin.registeredUsers": "Geregistreerde gebruikers",
    "admin.menusScanned": "Menu's gescand",
    "admin.differentPreferences": "Verschillende voorkeuren",
    "admin.adAnalytics": "Reclame Analytics",
    "admin.totalShown": "Totaal Getoond",
    "admin.completionRate": "Voltooiingspercentage",
    "admin.fullyWatched": "Volledig Bekeken",
    "admin.skipped": "Overgeslagen",
    "admin.avgSkipCountdown": "Gem. Skip Countdown",
    "admin.completionVsSkip": "Voltooiing vs. Skip",
    "admin.total": "{count} totaal",
    "admin.completed": "Volledig ({count})",
    "admin.skippedCount": "Overgeslagen ({count})",
    "admin.noAdAnalytics": "Nog geen reclame analytics beschikbaar",
    "admin.preferencesOverview": "Voorkeuren Overzicht",
    "admin.noPreferences": "Nog geen voorkeuren geregistreerd",
    "admin.loadingStats": "Statistieken laden...",
    "admin.noAccess": "Geen toegang",
    "admin.noAdminRights": "Je hebt geen admin rechten.",
    "admin.errorLoadingStats": "Kon statistieken niet laden.",
    
    // Common
    "common.loading": "Laden...",
    "common.error": "Fout",
    "common.success": "Gelukt",
    "common.back": "Terug",
    "common.close": "Sluiten",
    "common.save": "Opslaan",
    "common.cancel": "Annuleren",
    "common.delete": "Verwijderen",
    "common.edit": "Bewerken",
    "common.add": "Toevoegen",
    "common.login": "Inloggen",
    "common.continueAsGuest": "Doorgaan als Gast",
  },
  en: {
    // Index page
    "index.title": "Find your perfect meal",
    "index.subtitle": "Match your allergies and preferences with restaurants",
    "index.scanMenu": "Scan Menu",
    "index.myProfile": "My Profile",
    "index.signIn": "Sign In",
    "index.feature1Title": "Scan & Recognize",
    "index.feature1Desc": "Scan menus directly with your camera and let AI analyze the ingredients",
    "index.feature2Title": "Safety First",
    "index.feature2Desc": "Get immediate clear warnings for your specific allergies",
    "index.feature3Title": "Personal",
    "index.feature3Desc": "Save your allergies and preferences for faster checks",
    "index.howItWorksTitle": "How it works",
    "index.howItWorksDesc": "Safe dining in 3 simple steps",
    "index.step1Title": "Set your preferences",
    "index.step1Desc": "Add your allergies, dietary needs and preferences to your profile. You only need to do this once.",
    "index.step2Title": "Scan the menu",
    "index.step2Desc": "Use your camera to scan the menu, or upload a photo. Our AI does the rest.",
    "index.step3Title": "See immediately what's safe",
    "index.step3Desc": "Each dish gets a smiley: 😊 safe, 😐 adjustable, or 🤢 contains allergens.",
    "index.readyTitle": "Ready to enjoy safely?",
    "index.readyDesc": "Start scanning now and discover safe meals",
    
    // Allergies
    "allergy.noten": "Nuts",
    "allergy.gluten": "Gluten",
    "allergy.lactose": "Lactose",
    "allergy.schaaldieren": "Shellfish",
    "allergy.vis": "Fish",
    "allergy.eieren": "Eggs",
    "allergy.soja": "Soy",
    "allergy.sulfiet": "Sulfites",
    
    // Preferences
    "preference.vegetarisch": "Vegetarian",
    "preference.veganistisch": "Vegan",
    "preference.halal": "Halal",
    "preference.kosher": "Kosher",
    
    // Scan page
    "scan.title": "Scan Menu",
    "scan.subtitle": "Choose how to upload the menu",
    "scan.camera": "Camera",
    "scan.cameraDesc": "Scan directly with your camera",
    "scan.upload": "Upload",
    "scan.uploadDesc": "Upload a photo or PDF",
    "scan.multiple": "Multiple Photos",
    "scan.multipleDesc": "Combine different pages",
    "scan.analyzing": "Analyzing...",
    "scan.analyzingDesc": "AI is analyzing your menu. This may take a moment.",
    "scan.analyzingMultiple": "AI is analyzing {count} photo{s}. This may take a moment.",
    "scan.checkPhoto": "Check your photo",
    "scan.readable": "Is the menu clearly readable?",
    "scan.retry": "Retry",
    "scan.scanButton": "Scan",
    "scan.back": "Back",
    "scan.tipsTitle": "💡 Tips for best results:",
    "scan.tip1": "Ensure good lighting",
    "scan.tip2": "Hold the camera steady",
    "scan.tip3": "Make sure text is clearly readable",
    "scan.makePhoto": "Take a photo",
    "scan.position": "Position the menu in view",
    "scan.cancel": "Cancel",
    "scan.takePhoto": "Take Photo",
    "scan.multipleTitle": "Multiple Photos",
    "scan.photosAdded": "{count} photo{s} added",
    "scan.addPhotos": "Add photos of different menu pages",
    "scan.addMore": "Add More Photos",
    "scan.scanMultiple": "Scan {count} Photo{s}",
    "scan.page": "Page",
    "scan.errorTitle": "Oops, something went wrong",
    "scan.tryAgain": "Try Again",
    "scan.suggestionsTitle": "💡 Suggestions for better results:",
    "scan.suggestion1": "Ensure good lighting without shadows",
    "scan.suggestion2": "Hold the camera steady and directly above the menu",
    "scan.suggestion3": "Make sure the text is sharp and clearly readable",
    "scan.suggestion4": "Photograph the entire menu or a clear portion of it",
    
    // Menu Results
    "results.title": "Menu Results",
    "results.found": "{count} dishes found - Based on your preferences and allergies",
    "results.contains": "⚠️ Contains:",
    "results.safe": "Safe",
    "results.adjustable": "Adjustable",
    "results.containsAllergens": "Contains Allergens",
    "results.dishes": "dishes",
    
    // Profile page
    "profile.title": "My Profile",
    "profile.subtitle": "Set your allergies and preferences for personalized matches",
    "profile.businessSubtitle": "Manage your business settings",
    "profile.allergies": "🚫 Allergies",
    "profile.allergiesDesc": "Select all allergies we should consider",
    "profile.addCustom": "Add custom allergy",
    "profile.customDesc": "Add an allergy not in the list, including ingredients we should detect",
    "profile.allergyName": "Allergy name",
    "profile.allergyNamePlaceholder": "E.g: Sesame",
    "profile.characteristics": "Characteristics (comma separated)",
    "profile.characteristicsPlaceholder": "E.g: sesame seeds, sesame oil, tahini",
    "profile.characteristicsHelp": "These ingredients will be detected on menus",
    "profile.addAllergy": "Add Allergy",
    "profile.yourAllergies": "Your allergies:",
    "profile.preferences": "❤️ Dietary Preferences",
    "profile.preferencesDesc": "Select your dietary preferences",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.logout": "Logout",
    "profile.businessDashboard": "Business Dashboard",
    "profile.adminDashboard": "Admin Dashboard",
    "profile.saved": "Profile saved! ✓",
    "profile.savedDesc": "Your preferences have been updated successfully.",
    "profile.savedGuestDesc": "Your preferences have been temporarily saved.",
    
    // Auth page
    "auth.welcome": "Welcome to Bite Buddy",
    "auth.subtitle": "Match your allergies with perfect meals",
    "auth.userType": "I am a...",
    "auth.diner": "Diner",
    "auth.dinerDesc": "I'm looking for safe restaurants",
    "auth.business": "Restaurant",
    "auth.businessDesc": "I have a restaurant",
    "auth.signUp": "Sign Up",
    "auth.signIn": "Sign In",
    "auth.continueAsGuest": "Continue as Guest",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.alreadyAccount": "Already have an account?",
    "auth.noAccount": "Don't have an account?",
    "auth.signUpLink": "Sign Up",
    "auth.signInLink": "Sign In",
    
    // Menu View
    "menuView.title": "Menu",
    "menuView.dishesAvailable": "{count} dishes available",
    "menuView.noDishes": "This menu has no dishes yet",
    "menuView.yourAllergies": "Your allergies:",
    "menuView.compareAllergies": "Compare with my allergies",
    "menuView.comparing": "Comparing...",
    "menuView.results": "Results:",
    "menuView.foundAllergens": "Found allergens:",
    "menuView.otherAllergensWarning": "Contains other allergens. Ask staff for modifications.",
    "menuView.noDishesAdded": "This menu has no dishes added yet.",
    "menuView.loginRequired": "Login required",
    "menuView.loginRequiredDesc": "Log in to compare your allergies with the menu.",
    "menuView.loginToCompare": "Log in or continue as guest to compare your allergies with this menu",
    "menuView.menuNotFound": "Menu not found",
    "menuView.invalidQR": "This QR code is not valid.",
    "menuView.comparisonComplete": "Comparison complete!",
    "menuView.comparisonCompleteDesc": "Your allergies have been compared with the menu.",
    "menuView.errorScanning": "Error scanning",
    "menuView.errorLoading": "Error loading",
    "menuView.backToHome": "Back to Home",
    
    // Business Dashboard
    "business.title": "Business Dashboard",
    "business.subtitle": "View your menus and scan statistics",
    "business.totalMenus": "Total Menus",
    "business.totalScans": "Total Scans",
    "business.uniqueAllergies": "Unique Allergies/Preferences",
    "business.topAllergies": "Top 5 Allergies & Preferences",
    "business.topAllergiesDesc": "Most scanned allergies and preferences",
    "business.allAllergies": "All Allergies & Preferences",
    "business.allAllergiesDesc": "Complete list of scanned allergies and preferences",
    "business.timesScanned": "{count}x scanned",
    "business.myMenus": "My Menus",
    "business.myMenusDesc": "Manage your scanned menus and view QR codes",
    "business.noMenus": "You haven't scanned any menus yet",
    "business.scanFirstMenu": "Scan your first menu",
    "business.createdOn": "Created on {date}",
    "business.qrCode": "QR Code: {code}",
    "business.viewQR": "View QR",
    "business.addNewMenu": "Add New Menu",
    "business.addNewMenuDesc": "Pay €1.00 per menu to start scanning",
    "business.payAndScan": "Pay €1.00 and Scan Menu",
    "business.processingPayment": "Processing payment...",
    "business.noAccess": "No access",
    "business.businessOnly": "This page is for businesses only.",
    "business.notLoggedIn": "Not logged in",
    "business.loginToContinue": "Log in to continue",
    "business.paymentError": "Payment error",
    "business.backToProfile": "Back to Profile",
    
    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.subtitle": "Overview of app statistics",
    "admin.totalUsers": "Total Accounts",
    "admin.totalScans": "Total Scans",
    "admin.uniquePreferences": "Unique Preferences",
    "admin.registeredUsers": "Registered users",
    "admin.menusScanned": "Menus scanned",
    "admin.differentPreferences": "Different preferences",
    "admin.adAnalytics": "Ad Analytics",
    "admin.totalShown": "Total Shown",
    "admin.completionRate": "Completion Rate",
    "admin.fullyWatched": "Fully Watched",
    "admin.skipped": "Skipped",
    "admin.avgSkipCountdown": "Avg. Skip Countdown",
    "admin.completionVsSkip": "Completion vs. Skip",
    "admin.total": "{count} total",
    "admin.completed": "Completed ({count})",
    "admin.skippedCount": "Skipped ({count})",
    "admin.noAdAnalytics": "No ad analytics available yet",
    "admin.preferencesOverview": "Preferences Overview",
    "admin.noPreferences": "No preferences registered yet",
    "admin.loadingStats": "Loading statistics...",
    "admin.noAccess": "No access",
    "admin.noAdminRights": "You don't have admin rights.",
    "admin.errorLoadingStats": "Could not load statistics.",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.back": "Back",
    "common.close": "Close",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.login": "Sign In",
    "common.continueAsGuest": "Continue as Guest",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "en" || saved === "nl") ? saved : "nl";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
